// BanglaAIGuide — tools-data.js
// Logos via Clearbit API: https://logo.clearbit.com/{domain}
// No API key needed. Free to use.
// Fallback: Google Favicon API if Clearbit fails

const USD_TO_BDT = 122;

const tools = [

  // ── LLMs & CHATBOTS ──────────────────────────────────────────────
  {
    name: "ChatGPT",
    logo: "https://logo.clearbit.com/chatgpt.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=chatgpt.com&sz=64",
    category: "llm",
    pricing: "freemium",
    usdPrice: "Free / $8/mo (Go) / $20/mo (Plus) / $200/mo (Pro)",
    verified: "মার্চ ২০২৬",
    details: "Free tier available with limited usage (10 messages/5 hours). New Go plan launched 2026. Business plan $25-30/user/mo. Pricing adjustments in 2026.",
    description_bn: "OpenAI-এর সবচেয়ে জনপ্রিয় AI চ্যাটবট। লেখা, বিশ্লেষণ, কোড — সব কাজে দারুণ।",
    review_bn: "ফ্রিলান্সিংয়ের জন্য এটা দিয়ে ক্লায়েন্ট ইমেইল লিখি, অনেক সময় বাঁচে!",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.8,
    direct_url: "https://chatgpt.com",
    affiliate_url: "https://chatgpt.com",
    pricing_url: "https://openai.com/chatgpt/pricing",
    // Enhanced schema
    supportsBangla: true,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: true,
    dateAdded: "2024-01-01",
    bestFor: ["কন্টেন্ট রাইটিং", "কোড", "রিসার্চ", "ফ্রিল্যান্সিং"],
    difficultyLevel: "সহজ",
    tags: ["chatbot", "writing", "coding", "free"],
    similarTools: ["claude", "gemini", "grok"],
  },
  {
    name: "Claude",
    logo: "https://logo.clearbit.com/anthropic.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=anthropic.com&sz=64",
    category: "llm",
    pricing: "freemium",
    usdPrice: "Free / $20/mo (Pro) / $100-200/mo (Max)",
    verified: "মার্চ ২০২৬",
    details: "Free tier with limited usage. Max 5x at $100/mo, Max 20x at $200/mo. Team plan $25/user/mo. No recent pricing changes.",
    description_bn: "Anthropic-এর AI — বাংলায় কথা বলে, লম্বা ডকুমেন্ট বিশ্লেষণ করে, কোড লেখে।",
    review_bn: "বাংলা কন্টেন্ট তৈরিতে Claude আমার ফার্স্ট চয়েস। বাংলা বোঝে ভালো!",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.9,
    direct_url: "https://claude.ai",
    affiliate_url: "https://claude.ai",
    pricing_url: "https://claude.ai/pricing",
    // Enhanced schema
    supportsBangla: true,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: true,
    dateAdded: "2024-03-01",
    bestFor: ["বাংলা কন্টেন্ট", "ডকুমেন্ট বিশ্লেষণ", "কোড", "রাইটিং"],
    difficultyLevel: "সহজ",
    tags: ["chatbot", "writing", "coding", "bangla"],
    similarTools: ["chatgpt", "gemini", "perplexity-ai"],
  },
  {
    name: "Gemini",
    logo: "https://logo.clearbit.com/google.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=gemini.google.com&sz=64",
    category: "llm",
    pricing: "freemium",
    usdPrice: "Free / $19.99/mo (AI Pro) / ~$42/mo (AI Ultra)",
    verified: "মার্চ ২০২৬",
    details: "Free tier available. AI Ultra is $124.99 for 3 months. Includes Google Workspace integration. No major pricing changes.",
    description_bn: "Google-এর AI মডেল। ইন্টারনেট সার্চ যুক্ত, বাংলা ভাষায় ভালো সাপোর্ট।",
    review_bn: "Google Docs-এর সাথে ইন্টিগ্রেশন অসাধারণ। কাজ অনেক দ্রুত হয়।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.6,
    direct_url: "https://gemini.google.com",
    affiliate_url: "https://gemini.google.com",
    pricing_url: "https://one.google.com/about/plans",
    // Enhanced schema
    supportsBangla: true,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: true,
    dateAdded: "2024-06-01",
    bestFor: ["গুগল ওয়ার্কস্পেস", "বাংলা", "রিসার্চ", "কোড"],
    difficultyLevel: "সহজ",
    tags: ["chatbot", "google", "free", "bangla"],
    similarTools: ["chatgpt", "claude", "perplexity-ai"],
  },
  {
    name: "Perplexity AI",
    logo: "https://logo.clearbit.com/perplexity.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=perplexity.ai&sz=64",
    category: "llm",
    pricing: "freemium",
    usdPrice: "Free / $20/mo (Pro) / $200/mo (Max)",
    verified: "মার্চ ২০২৬",
    details: "Free plan with 5 Pro searches/day. Enterprise Pro $40/seat/mo, Enterprise Max $325/seat/mo. Stable pricing.",
    description_bn: "AI দিয়ে ওয়েব সার্চ — সোর্স সহ উত্তর দেয়। রিসার্চ কাজে সেরা।",
    review_bn: "রিসার্চের জন্য এটাই ব্যবহার করি। কোথা থেকে তথ্য নিয়েছে সেটাও দেখায়।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.7,
    direct_url: "https://www.perplexity.ai",
    affiliate_url: "https://www.perplexity.ai",
    pricing_url: "https://www.perplexity.ai/pro",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-03-01",
    bestFor: ["রিসার্চ", "ওয়েব সার্চ", "তথ্য যাচাই"],
    difficultyLevel: "সহজ",
    tags: ["search", "research", "free"],
    similarTools: ["chatgpt", "gemini", "notebooklm"],
  },
  {
    name: "Groq",
    logo: "https://logo.clearbit.com/groq.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=groq.com&sz=64",
    category: "llm",
    pricing: "freemium",
    usdPrice: "Free / Pay-as-you-go (API)",
    verified: "মার্চ ২০২৬",
    details: "Free tier available. Developer plan is pay-as-you-go ($0.06-0.99 per million tokens). 50% discount for batch API. Very low pricing.",
    description_bn: "বিদ্যুৎ গতির LLM inference। Llama ও Mixtral মডেল চালায়।",
    review_bn: "API কলে সবচেয়ে দ্রুত রেসপন্স পাই। বাংলাদেশ থেকে কোনো সমস্যা নেই।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.4,
    direct_url: "https://groq.com",
    affiliate_url: "https://groq.com",
    pricing_url: "https://groq.com",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: false,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-06-01",
    bestFor: ["দ্রুত API", "ডেভেলপার", "ওপেনসোর্স মডেল"],
    difficultyLevel: "কঠিন",
    tags: ["api", "developer", "fast", "free"],
    similarTools: ["mistral-ai", "huggingchat", "deepseek"],
  },
  {
    name: "Mistral AI",
    logo: "https://logo.clearbit.com/mistral.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=mistral.ai&sz=64",
    category: "llm",
    pricing: "freemium",
    usdPrice: "Free / $14.99/mo (Le Chat Pro) / Pay-as-you-go (API)",
    verified: "মার্চ ২০২৬",
    details: "Free tier for Le Chat. Pro plan $14.99/mo. API pricing varies by model ($0.02-2.00 per million input tokens).",
    description_bn: "ইউরোপের সেরা ওপেনসোর্স LLM। ডেটা প্রাইভেসি ভালো, cost-effective।",
    review_bn: "ChatGPT-এর ভালো বিকল্প। ফ্রিতে অনেক কাজ হয়।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.3,
    direct_url: "https://mistral.ai",
    affiliate_url: "https://mistral.ai",
    pricing_url: "https://mistral.ai",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: false,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-03-01",
    bestFor: ["প্রাইভেসি", "ইউরোপিয়ান AI", "API", "ডেভেলপার"],
    difficultyLevel: "মধ্যম",
    tags: ["opensource", "api", "privacy", "free"],
    similarTools: ["groq", "deepseek", "huggingchat"],
  },
  {
    name: "Poe",
    logo: "https://logo.clearbit.com/poe.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=poe.com&sz=64",
    category: "llm",
    pricing: "freemium",
    usdPrice: "Free / $17/mo (Premium)",
    verified: "মার্চ ২০২৬",
    details: "Free plan with limited daily credits. Premium plans start at $4.99/mo, full access ~$17/mo. Multi-model access platform.",
    description_bn: "এক জায়গায় GPT-4, Claude, Gemini সব। নিজের বট তৈরি করা যায়।",
    review_bn: "একটা অ্যাপ দিয়ে সব AI ব্যবহার করা যায় — এটাই সবচেয়ে সুবিধা।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.3,
    direct_url: "https://poe.com",
    affiliate_url: "https://poe.com",
    pricing_url: "https://poe.com",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-01-01",
    bestFor: ["মাল্টি-মডেল", "বট তৈরি", "এক্সপেরিমেন্ট"],
    difficultyLevel: "সহজ",
    tags: ["multi-model", "chatbot", "free"],
    similarTools: ["chatgpt", "claude", "gemini"],
  },
  {
    name: "Meta AI",
    logo: "https://logo.clearbit.com/meta.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=meta.ai&sz=64",
    category: "llm",
    pricing: "free",
    usdPrice: "Free",
    verified: "মার্চ ২০২৬",
    details: "Completely free. Integrated into Facebook, Instagram, WhatsApp. No paid tiers.",
    description_bn: "Meta-র Llama AI — WhatsApp ও Instagram-এ বিল্টইন। বাংলায়ও কথা বলে।",
    review_bn: "WhatsApp-এ সরাসরি ব্যবহার করা যায়। বাংলায় উত্তর দেয়!",
    works_in_bd: true, no_vpn: true, payment: "free", rating: 4.1,
    direct_url: "https://www.meta.ai",
    affiliate_url: "https://www.meta.ai",
    pricing_url: "https://www.meta.ai",
    // Enhanced schema
    supportsBangla: true,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-06-01",
    bestFor: ["WhatsApp", "ফেসবুক", "বাংলা", "দৈনন্দিন কাজ"],
    difficultyLevel: "সহজ",
    tags: ["free", "whatsapp", "bangla", "social"],
    similarTools: ["chatgpt", "gemini", "grok"],
  },
  {
    name: "HuggingChat",
    logo: "https://logo.clearbit.com/huggingface.co",
    logo_fallback: "https://www.google.com/s2/favicons?domain=huggingface.co&sz=64",
    category: "llm",
    pricing: "free",
    usdPrice: "সম্পূর্ণ ফ্রি",
    verified: "মার্চ ২০২৬",
    description_bn: "Hugging Face-এর ফ্রি chatbot। ওপেনসোর্স মডেল, ডেটা কোথাও বিক্রি হয় না।",
    review_bn: "যাদের বাজেট কম তাদের জন্য দারুণ অপশন। সম্পূর্ণ ফ্রি!",
    works_in_bd: true, no_vpn: true, payment: "free", rating: 4.0,
    direct_url: "https://huggingface.co/chat",
    affiliate_url: "https://huggingface.co/chat",
    pricing_url: "https://huggingface.co/chat",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: false,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-01-01",
    bestFor: ["ওপেনসোর্স", "প্রাইভেসি", "ফ্রি AI"],
    difficultyLevel: "মধ্যম",
    tags: ["opensource", "free", "privacy"],
    similarTools: ["groq", "mistral-ai", "deepseek"],
  },
  {
    name: "DeepSeek",
    logo: "https://logo.clearbit.com/deepseek.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=deepseek.com&sz=64",
    category: "llm",
    pricing: "free",
    usdPrice: "সম্পূর্ণ ফ্রি",
    verified: "মার্চ ২০২৬",
    description_bn: "চীনের DeepSeek — কোডিং ও ম্যাথে ChatGPT-4 এর চেয়ে ভালো। রিজনিং মডেল সম্পূর্ণ ফ্রি।",
    review_bn: "কোডিং সমস্যা সমাধানে এটি এখন আমার প্রথম পছন্দ। ফ্রি অথচ শক্তিশালী!",
    works_in_bd: true, no_vpn: true, payment: "free", rating: 4.7,
    direct_url: "https://chat.deepseek.com",
    affiliate_url: "https://chat.deepseek.com",
    pricing_url: "https://chat.deepseek.com",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: true,
    dateAdded: "2025-01-01",
    bestFor: ["কোডিং", "ম্যাথ", "ফ্রি AI", "রিজনিং"],
    difficultyLevel: "সহজ",
    tags: ["free", "coding", "math", "reasoning"],
    similarTools: ["chatgpt", "groq", "huggingchat"],
  },
  {
    name: "Grok",
    logo: "https://logo.clearbit.com/x.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=grok.com&sz=64",
    category: "llm",
    pricing: "freemium",
    usdPrice: "Free (limited) / $30/mo (SuperGrok)",
    verified: "মার্চ ২০২৬",
    details: "Free tier on X with limitations. SuperGrok $30/mo includes Grok 3, Grok Imagine (AI images), DeepSearch and unlimited access.",
    description_bn: "Elon Musk এর AI — X/Twitter থেকে real-time তথ্য পায়, ফ্রিতে AI ছবি তৈরি করা যায়",
    review_bn: "সাম্প্রতিক খবর ও real-time তথ্যের জন্য Grok-এর বিকল্প নেই।",
    works_in_bd: true, no_vpn: true, payment: "free", rating: 4.5,
    direct_url: "https://grok.com",
    affiliate_url: "https://grok.com",
    pricing_url: "https://x.ai/grok",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-06-01",
    bestFor: ["রিয়েল-টাইম তথ্য", "X/Twitter", "AI ছবি", "সংবাদ"],
    difficultyLevel: "সহজ",
    tags: ["realtime", "free", "image", "twitter"],
    similarTools: ["chatgpt", "perplexity-ai", "meta-ai"],
  },

  // ── IMAGE & VIDEO ─────────────────────────────────────────────────
  {
    name: "Midjourney",
    logo: "https://logo.clearbit.com/midjourney.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=midjourney.com&sz=64",
    category: "image",
    pricing: "paid",
    usdPrice: "$10/mo (Basic) / $30/mo (Standard) / $60/mo (Pro) / $120/mo (Mega)",
    verified: "মার্চ ২০২৬",
    details: "No free tier. Annual billing saves 20%. Stealth Mode (privacy) requires Pro plan minimum. No recent pricing changes.",
    description_bn: "বিশ্বের সেরা AI আর্ট জেনারেটর। Discord-এর মাধ্যমে ব্যবহার।",
    review_bn: "ফ্রিল্যান্স গ্রাফিক কাজে এটা দিয়ে অনেক ক্লায়েন্ট পেয়েছি!",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.9,
    direct_url: "https://www.midjourney.com",
    affiliate_url: "https://www.midjourney.com",
    pricing_url: "https://www.midjourney.com/account",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: false,
    mobileFriendly: false,
    beginnerFriendly: false,
    paymentAccessibility: "easy",
    featured: true,
    dateAdded: "2024-01-01",
    bestFor: ["গ্রাফিক ডিজাইন", "আর্ট", "ফ্রিল্যান্সিং", "ক্রিয়েটিভ"],
    difficultyLevel: "মধ্যম",
    tags: ["image", "art", "design", "discord"],
    similarTools: ["ideogram", "leonardo-ai", "flux"],
  },
  {
    name: "Ideogram",
    logo: "https://logo.clearbit.com/ideogram.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=ideogram.ai&sz=64",
    category: "image",
    pricing: "freemium",
    usdPrice: "Free / $16/mo (Plus)",
    verified: "মার্চ ২০২৬",
    details: "Free tier available and genuinely usable. Plus plan $16/mo for private generation. Excellent text rendering.",
    description_bn: "ছবিতে টেক্সট লেখার জন্য সেরা AI। থাম্বনেইল ও পোস্টার তৈরিতে অপ্রতিদ্বন্দ্বী।",
    review_bn: "YouTube থাম্বনেইলের জন্য এটা use করি। বাংলা টেক্সটও সুন্দর আসে!",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.6,
    direct_url: "https://ideogram.ai",
    affiliate_url: "https://ideogram.ai",
    pricing_url: "https://ideogram.ai/pricing",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-06-01",
    bestFor: ["থাম্বনেইল", "পোস্টার", "টেক্সট ইন ইমেজ", "YouTube"],
    difficultyLevel: "সহজ",
    tags: ["image", "text", "thumbnail", "free"],
    similarTools: ["midjourney", "adobe-firefly", "flux"],
  },
  {
    name: "Kling AI",
    logo: "https://logo.clearbit.com/klingai.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=klingai.com&sz=64",
    category: "image",
    pricing: "freemium",
    usdPrice: "~$10/mo (via Artlist)",
    verified: "মার্চ ২০২৬",
    details: "Accessible through Artlist platform. Strong image-to-video generation. Pricing competitive with market.",
    description_bn: "হাই-কোয়ালিটি AI ভিডিও জেনারেটর। টেক্সট-টু-ভিডিও ও ইমেজ অ্যানিমেশন।",
    review_bn: "বাংলা অ্যানিমেশন কন্টেন্টের জন্য এটা ব্যবহার করছি। রেজাল্ট দারুণ!",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.5,
    direct_url: "https://klingai.com",
    affiliate_url: "https://klingai.com",
    pricing_url: "https://klingai.com/pricing",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: false,
    mobileFriendly: true,
    beginnerFriendly: false,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2025-01-01",
    bestFor: ["AI ভিডিও", "অ্যানিমেশন", "ইমেজ-টু-ভিডিও"],
    difficultyLevel: "মধ্যম",
    tags: ["video", "animation", "image-to-video"],
    similarTools: ["runway-ml", "suno-ai", "descript"],
  },
  {
    name: "Runway ML",
    logo: "https://logo.clearbit.com/runwayml.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=runwayml.com&sz=64",
    category: "image",
    pricing: "freemium",
    usdPrice: "Free (125 credits) / $12/mo (Standard)",
    verified: "মার্চ ২০২৬",
    details: "Free tier with 125 one-time credits. Standard plan $12/mo (annual billing). Gen-4 model available.",
    description_bn: "প্রফেশনাল AI ভিডিও এডিটিং ও জেনারেশন। Gen-2 মডেল দিয়ে অবাক করা ভিডিও।",
    review_bn: "ইউটিউব কন্টেন্টে B-roll তৈরিতে দারুণ। সময় ও টাকা দুটোই বাঁচে।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.6,
    direct_url: "https://runwayml.com",
    affiliate_url: "https://runwayml.com",
    pricing_url: "https://runwayml.com/pricing",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: false,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-01-01",
    bestFor: ["ভিডিও এডিটিং", "B-roll", "YouTube", "ভিডিও জেনারেশন"],
    difficultyLevel: "মধ্যম",
    tags: ["video", "editing", "ai-video"],
    similarTools: ["kling-ai", "descript", "suno-ai"],
  },
  {
    name: "Leonardo AI",
    logo: "https://logo.clearbit.com/leonardo.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=leonardo.ai&sz=64",
    category: "image",
    pricing: "freemium",
    usdPrice: "Free (150 tokens/day) / $10/mo (Apprentice) / $24/mo (Artisan) / $48/mo (Maestro)",
    verified: "মার্চ ২০২৬",
    details: "Free tier with 150 daily tokens. Token-based pricing system. Commercial rights on paid plans.",
    description_bn: "গেম অ্যাসেট, ইলাস্ট্রেশন ও কনসেপ্ট আর্টের জন্য ফাইন-টিউন মডেল।",
    review_bn: "ফ্রি টায়ারে প্রতিদিন ১৫০ ক্রেডিট পাওয়া যায়। কোনো সমস্যা নেই!",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.5,
    direct_url: "https://leonardo.ai",
    affiliate_url: "https://leonardo.ai",
    pricing_url: "https://leonardo.ai/pricing",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-03-01",
    bestFor: ["গেম অ্যাসেট", "ইলাস্ট্রেশন", "কনসেপ্ট আর্ট"],
    difficultyLevel: "মধ্যম",
    tags: ["image", "game", "illustration", "free"],
    similarTools: ["midjourney", "ideogram", "stable-diffusion"],
  },
  {
    name: "Stable Diffusion",
    logo: "https://logo.clearbit.com/stability.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=stability.ai&sz=64",
    category: "image",
    pricing: "free",
    usdPrice: "সম্পূর্ণ ফ্রি",
    verified: "মার্চ ২০২৬",
    description_bn: "ওপেনসোর্স ইমেজ মডেল — নিজের PC-তে চালানো যায়। সর্বোচ্চ কাস্টমাইজেশন।",
    review_bn: "লোকালি চালাই, তাই কোনো API খরচ নেই।",
    works_in_bd: true, no_vpn: true, payment: "free", rating: 4.5,
    direct_url: "https://stability.ai",
    affiliate_url: "https://stability.ai",
    pricing_url: "https://stability.ai",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: false,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-01-01",
    bestFor: ["লোকাল AI", "ওপেনসোর্স", "কাস্টম মডেল"],
    difficultyLevel: "কঠিন",
    tags: ["image", "opensource", "local", "free"],
    similarTools: ["flux", "leonardo-ai", "adobe-firefly"],
  },
  {
    name: "Adobe Firefly",
    logo: "https://logo.clearbit.com/adobe.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=firefly.adobe.com&sz=64",
    category: "image",
    pricing: "freemium",
    usdPrice: "Free / $9.99/mo (Standard) / $19.99/mo (Pro) / $199.99/mo (Premium)",
    verified: "মার্চ ২০২৬",
    details: "Free tier available. Credit-based system. Unlimited standard generations on paid plans. Integrated with Creative Cloud.",
    description_bn: "Adobe-র কমার্শিয়ালি সেফ AI। Photoshop ও Illustrator-এর সাথে ইন্টিগ্রেটেড।",
    review_bn: "ফ্রিলান্স ডিজাইন কাজে কমার্শিয়াল লাইসেন্সের চিন্তা নেই।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.3,
    direct_url: "https://firefly.adobe.com",
    affiliate_url: "https://firefly.adobe.com",
    pricing_url: "https://firefly.adobe.com",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-03-01",
    bestFor: ["কমার্শিয়াল ডিজাইন", "Photoshop", "ফ্রিল্যান্স"],
    difficultyLevel: "সহজ",
    tags: ["image", "commercial", "adobe", "design"],
    similarTools: ["midjourney", "ideogram", "stable-diffusion"],
  },
  {
    name: "Flux",
    logo: "https://logo.clearbit.com/blackforestlabs.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=blackforestlabs.ai&sz=64",
    category: "image",
    pricing: "freemium",
    usdPrice: "Free / API paid",
    verified: "মার্চ ২০২৬",
    description_bn: "Black Forest Labs-এর স্টেট-অফ-দ্যা-আর্ট ইমেজ মডেল। অত্যন্ত রিয়েলিস্টিক।",
    review_bn: "Midjourney-র বিকল্প হিসেবে ব্যবহার শুরু করেছি। কোয়ালিটি অসাধারণ!",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.6,
    direct_url: "https://blackforestlabs.ai",
    affiliate_url: "https://blackforestlabs.ai",
    pricing_url: "https://blackforestlabs.ai",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: false,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-09-01",
    bestFor: ["রিয়েলিস্টিক ইমেজ", "ফটো এডিটিং", "API"],
    difficultyLevel: "মধ্যম",
    tags: ["image", "realistic", "api"],
    similarTools: ["midjourney", "stable-diffusion", "leonardo-ai"],
  },

  // ── CODING ────────────────────────────────────────────────────────
  {
    name: "Cursor",
    logo: "https://logo.clearbit.com/cursor.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=cursor.com&sz=64",
    category: "coding",
    pricing: "freemium",
    usdPrice: "Free / $20/mo (Pro)",
    verified: "মার্চ ২০২৬",
    details: "Free tier available. Pro plan $20/mo for advanced AI features. AI-native code editor fork of VS Code.",
    description_bn: "AI-ফার্স্ট কোড এডিটর। স্বাভাবিক ভাষায় কোড লিখুন, এডিট করুন, ডিবাগ করুন।",
    review_bn: "এই একটা টুল দিয়ে আমার কোডিং স্পিড ৩ গুণ বেড়েছে!",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.9,
    direct_url: "https://cursor.com",
    affiliate_url: "https://cursor.com/affiliates",
    pricing_url: "https://cursor.com/pricing",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: false,
    paymentAccessibility: "easy",
    featured: true,
    dateAdded: "2024-01-01",
    bestFor: ["কোডিং", "ডেভেলপমেন্ট", "ফ্রিল্যান্স ডেভেলপার"],
    difficultyLevel: "মধ্যম",
    tags: ["coding", "ide", "developer"],
    similarTools: ["github-copilot", "windsurf", "claude-code"],
  },
  {
    name: "GitHub Copilot",
    logo: "https://logo.clearbit.com/github.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=github.com&sz=64",
    category: "coding",
    pricing: "freemium",
    usdPrice: "Free (limited) / $10/mo (Individual) / $19/user/mo (Business)",
    verified: "মার্চ ২০২৬",
    details: "Free tier with 2,000 completions. Students/open-source free. Half the price of Cursor at every tier.",
    description_bn: "IDE-র ভেতরেই AI পেয়ার প্রোগ্রামার। অটোকমপ্লিট, চ্যাট ও কোড রিভিউ।",
    review_bn: "VS Code-এ কাজ করি, Copilot থেকে আর বের হতে পারি না!",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.7,
    direct_url: "https://github.com/features/copilot",
    affiliate_url: "https://github.com/features/copilot",
    pricing_url: "https://github.com/features/copilot#pricing",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: false,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-01-01",
    bestFor: ["কোড অটোকমপ্লিট", "VS Code", "IDE"],
    difficultyLevel: "মধ্যম",
    tags: ["coding", "autocomplete", "github"],
    similarTools: ["cursor", "windsurf", "replit-ai"],
  },
  {
    name: "Bolt.new",
    logo: "https://logo.clearbit.com/bolt.new",
    logo_fallback: "https://www.google.com/s2/favicons?domain=bolt.new&sz=64",
    category: "coding",
    pricing: "freemium",
    usdPrice: "Free tier / Paid plans available",
    verified: "মার্চ ২০২৬",
    details: "Free tier available for testing. Paid plans for production use. StackBlitz-powered vibe coding platform.",
    description_bn: "ব্রাউজারেই ফুল-স্ট্যাক অ্যাপ বানান। কোনো সেটআপ ছাড়াই প্রম্পট দিয়ে অ্যাপ।",
    review_bn: "ক্লায়েন্টকে ডেমো দেওয়ার জন্য ১ ঘন্টায় পুরো অ্যাপ বানাই!",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.5,
    direct_url: "https://bolt.new",
    affiliate_url: "https://bolt.new",
    pricing_url: "https://bolt.new/pricing",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-09-01",
    bestFor: ["ভাইব কোডিং", "প্রোটোটাইপ", "ডেমো অ্যাপ"],
    difficultyLevel: "সহজ",
    tags: ["coding", "no-code", "webapp", "free"],
    similarTools: ["lovable", "v0-by-vercel", "replit-ai"],
  },
  {
    name: "v0 by Vercel",
    logo: "https://logo.clearbit.com/vercel.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=v0.dev&sz=64",
    category: "coding",
    pricing: "freemium",
    usdPrice: "Free ($5 credits) / $20/mo",
    verified: "মার্চ ২০২৬",
    details: "Free tier with $5 compute credits. Paid plan $20/mo for individuals. React/Next.js focused UI generator.",
    description_bn: "প্রম্পট থেকে React + Tailwind UI কম্পোনেন্ট। Vercel-এ ইনস্ট্যান্ট ডিপ্লয়।",
    review_bn: "UI ডিজাইনের জন্য ফ্রন্টএন্ড ডেভেলপার লাগে না আর।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.5,
    direct_url: "https://v0.dev",
    affiliate_url: "https://v0.dev",
    pricing_url: "https://v0.dev",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: false,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-06-01",
    bestFor: ["UI কম্পোনেন্ট", "React", "Next.js", "ফ্রন্টেন্ড"],
    difficultyLevel: "মধ্যম",
    tags: ["coding", "react", "ui", "frontend"],
    similarTools: ["bolt-new", "lovable", "cursor"],
  },
  {
    name: "Windsurf",
    logo: "https://logo.clearbit.com/windsurf.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=windsurf.com&sz=64",
    category: "coding",
    pricing: "freemium",
    usdPrice: "Free (individuals) / $15/mo",
    verified: "মার্চ ২০২৬",
    details: "Free tier for individual developers. $15/mo for paid plan. Competitive with Cursor and Copilot.",
    description_bn: "Codeium-এর AI কোড এডিটর। 'Flow' ফিচার দিয়ে পুরো প্রজেক্ট এজেন্টিকভাবে বানায়।",
    review_bn: "Cursor-এর ভালো ফ্রি বিকল্প। বাংলাদেশ থেকে কোনো সমস্যা নেই।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.5,
    direct_url: "https://windsurf.com",
    affiliate_url: "https://windsurf.com",
    pricing_url: "https://windsurf.com",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: false,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-09-01",
    bestFor: ["কোডিং", "এজেন্টিক কোডিং", "ফ্রি IDE"],
    difficultyLevel: "মধ্যম",
    tags: ["coding", "ide", "free", "developer"],
    similarTools: ["cursor", "github-copilot", "claude-code"],
  },
  {
    name: "Replit AI",
    logo: "https://logo.clearbit.com/replit.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=replit.com&sz=64",
    category: "coding",
    pricing: "freemium",
    usdPrice: "Free (Starter) / $20-25/mo (Core) / $100/mo (Pro)",
    verified: "মার্চ ২০২৬",
    details: "Free Starter plan. Core $20/mo (annual) or $25/mo (monthly). New Pro plan $100/mo for teams up to 15 users. Usage-based credits.",
    description_bn: "ব্রাউজার-বেসড IDE + AI। ইনস্ট্যান্ট ডেভেলপমেন্ট এনভায়রনমেন্ট।",
    review_bn: "কম্পিউটারে সেটআপ ছাড়াই কোড লেখা ও রান করা যায়।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.2,
    direct_url: "https://replit.com",
    affiliate_url: "https://replit.com",
    pricing_url: "https://replit.com/pricing",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-01-01",
    bestFor: ["শিক্ষার্থী", "ব্রাউজার কোডিং", "শিখতে"],
    difficultyLevel: "সহজ",
    tags: ["coding", "browser", "learning", "free"],
    similarTools: ["bolt-new", "github-copilot", "cursor"],
  },
  {
    name: "Claude Code",
    logo: "https://logo.clearbit.com/anthropic.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=anthropic.com&sz=64",
    category: "coding",
    pricing: "paid",
    usdPrice: "Usage-based",
    verified: "মার্চ ২০২৬",
    description_bn: "Anthropic-এর টার্মিনাল AI। পুরো প্রজেক্ট প্ল্যান করে, কোড লেখে, ডিবাগ করে।",
    review_bn: "SaaS প্রজেক্টের জন্য এটা ব্যবহার করছি। সত্যিকারের এজেন্টিক কোডিং।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.7,
    direct_url: "https://claude.ai/code",
    affiliate_url: "https://claude.ai/code",
    pricing_url: "https://claude.ai/code",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: false,
    mobileFriendly: false,
    beginnerFriendly: false,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2025-01-01",
    bestFor: ["এজেন্টিক কোডিং", "SaaS", "টার্মিনাল"],
    difficultyLevel: "কঠিন",
    tags: ["coding", "agentic", "terminal", "anthropic"],
    similarTools: ["cursor", "windsurf", "github-copilot"],
  },
  {
    name: "Lovable",
    logo: "https://logo.clearbit.com/lovable.dev",
    logo_fallback: "https://www.google.com/s2/favicons?domain=lovable.dev&sz=64",
    category: "coding",
    pricing: "freemium",
    usdPrice: "Free / $20/mo (Pro)",
    verified: "মার্চ ২০২৬",
    description_bn: "প্রম্পট লিখুন → পুরো ওয়েব অ্যাপ তৈরি হয়ে যাবে। কোডিং জানা লাগবে না।",
    review_bn: "বললাম 'একটা expense tracker বানাও' — ৩০ সেকেন্ডে পুরো অ্যাপ রেডি!",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.6,
    direct_url: "https://lovable.dev",
    affiliate_url: "https://lovable.dev",
    pricing_url: "https://lovable.dev/pricing",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-09-01",
    bestFor: ["নো-কোড অ্যাপ", "ভাইব কোডিং", "স্টার্টআপ"],
    difficultyLevel: "সহজ",
    tags: ["coding", "no-code", "webapp", "free"],
    similarTools: ["bolt-new", "v0-by-vercel", "replit-ai"],
  },

  // ── PRODUCTIVITY ──────────────────────────────────────────────────
  {
    name: "ElevenLabs",
    logo: "https://logo.clearbit.com/elevenlabs.io",
    logo_fallback: "https://www.google.com/s2/favicons?domain=elevenlabs.io&sz=64",
    category: "productivity",
    pricing: "freemium",
    usdPrice: "Free (10k credits) / $1/mo (Starter promo) / $11-22/mo (Creator)",
    verified: "মার্চ ২০২৬",
    details: "Free tier with 10k credits. Promotional pricing available (50-80% off). Creator plan normally $22/mo. Professional voice cloning on paid plans.",
    description_bn: "সেরা AI ভয়েস সিন্থেসিস। ভয়েস ক্লোনিং, টেক্সট-টু-স্পিচ ২৯টি ভাষায়।",
    review_bn: "বাংলা পডকাস্ট ও ভয়েসওভারের জন্য দারুণ। বাংলা উচ্চারণও বেশ ভালো!",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.8,
    direct_url: "https://elevenlabs.io",
    affiliate_url: "https://try.elevenlabs.io/zrypgupkyu99",
    pricing_url: "https://elevenlabs.io/pricing",
    // Enhanced schema
    supportsBangla: true,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-01-01",
    bestFor: ["ভয়েসওভার", "পডকাস্ট", "বাংলা TTS", "ভয়েস ক্লোনিং"],
    difficultyLevel: "সহজ",
    tags: ["voice", "tts", "bangla", "podcast"],
    similarTools: ["suno-ai", "descript", "otter-ai"],
  },
  {
    name: "Gamma",
    logo: "https://logo.clearbit.com/gamma.app",
    logo_fallback: "https://www.google.com/s2/favicons?domain=gamma.app&sz=64",
    category: "productivity",
    pricing: "freemium",
    usdPrice: "Free (400 credits) / $8/mo (Plus) / $15-20/mo (Pro) / $100/mo (Ultra)",
    verified: "মার্চ ২০২৬",
    details: "Free plan with 400 AI credits. Plus $8/mo (annual) or $10/mo (monthly). AI presentation maker. No recent pricing changes.",
    description_bn: "AI দিয়ে প্রেজেন্টেশন বানান। একটা প্রম্পট থেকে পুরো স্লাইড ডেক।",
    review_bn: "ক্লায়েন্ট পিচের জন্য ৩০ মিনিটে প্রফেশনাল প্রেজেন্টেশন বানাই।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.6,
    direct_url: "https://gamma.app",
    affiliate_url: "https://gamma.app",
    pricing_url: "https://gamma.app/pricing",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-01-01",
    bestFor: ["প্রেজেন্টেশন", "পিচ ডেক", "স্লাইড"],
    difficultyLevel: "সহজ",
    tags: ["presentation", "slides", "free"],
    similarTools: ["notion-ai", "jasper-ai"],
  },
  {
    name: "Notion AI",
    logo: "https://logo.clearbit.com/notion.so",
    logo_fallback: "https://www.google.com/s2/favicons?domain=notion.so&sz=64",
    category: "productivity",
    pricing: "freemium",
    usdPrice: "Limited trial / Included in Business ($20/user/mo)",
    verified: "মার্চ ২০২৬",
    details: "AI features included in Business ($20/user/mo) and Enterprise plans. Free/Plus users get limited trial. Integrated AI approach.",
    description_bn: "Notion ওয়ার্কস্পেসে বিল্টইন AI। লেখা, সারসংক্ষেপ, ব্রেইনস্টর্মিং।",
    review_bn: "সব কন্টেন্ট প্ল্যানিং Notion-এ করি। AI ফিচার দিয়ে অনেক দ্রুত হয়।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.5,
    direct_url: "https://notion.so/product/ai",
    affiliate_url: "https://notion.so/affiliates",
    pricing_url: "https://www.notion.so/pricing",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: false,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-01-01",
    bestFor: ["কন্টেন্ট প্ল্যানিং", "নোট নেওয়া", "প্রজেক্ট ম্যানেজমেন্ট"],
    difficultyLevel: "সহজ",
    tags: ["productivity", "notes", "workspace"],
    similarTools: ["gamma", "jasper-ai", "otter-ai"],
  },
  {
    name: "Suno AI",
    logo: "https://logo.clearbit.com/suno.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=suno.com&sz=64",
    category: "productivity",
    pricing: "freemium",
    usdPrice: "Free (50 credits/day) / $10/mo (Pro) / $30/mo (Premier)",
    verified: "মার্চ ২০২৬",
    details: "Free tier with 50 daily credits. Pro $10/mo ($8 annually), Premier $30/mo. Commercial rights on paid plans.",
    description_bn: "টেক্সট থেকে পুরো গান তৈরি। লিরিক্স, মিউজিক, ভোকাল — সব AI দিয়ে।",
    review_bn: "ইউটিউব ভিডিওর জন্য ব্যাকগ্রাউন্ড মিউজিক তৈরি করি। কপিরাইট সমস্যা নেই।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.6,
    direct_url: "https://suno.com",
    affiliate_url: "https://suno.com",
    pricing_url: "https://suno.com/pricing",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-03-01",
    bestFor: ["মিউজিক", "ব্যাকগ্রাউন্ড মিউজিক", "গান তৈরি", "YouTube"],
    difficultyLevel: "সহজ",
    tags: ["music", "audio", "free"],
    similarTools: ["elevenlabs", "descript"],
  },
  {
    name: "Descript",
    logo: "https://logo.clearbit.com/descript.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=descript.com&sz=64",
    category: "productivity",
    pricing: "freemium",
    usdPrice: "Free (1 hour) / $24/user/mo (Hobbyist)",
    verified: "মার্চ ২০২৬",
    details: "Free plan with 1 hour transcription. Hobbyist $24/mo with 10 hours, 1080p export. AI video/podcast editor.",
    description_bn: "AI ভিডিও ও পডকাস্ট এডিটর। টেক্সট ডকুমেন্টের মতো ভিডিও এডিট করুন।",
    review_bn: "পডকাস্ট রেকর্ড করে Descript-এ এডিট করি। অনেক সহজ হয়ে গেছে।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.4,
    direct_url: "https://www.descript.com",
    affiliate_url: "https://www.descript.com",
    pricing_url: "https://www.descript.com/pricing",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-01-01",
    bestFor: ["পডকাস্ট এডিটিং", "ভিডিও এডিটিং", "ট্রান্সক্রিপশন"],
    difficultyLevel: "সহজ",
    tags: ["video", "podcast", "editing", "transcription"],
    similarTools: ["otter-ai", "elevenlabs", "runway-ml"],
  },
  {
    name: "Otter.ai",
    logo: "https://logo.clearbit.com/otter.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=otter.ai&sz=64",
    category: "productivity",
    pricing: "freemium",
    usdPrice: "Free / $17/mo",
    verified: "মার্চ ২০২৬",
    description_bn: "রিয়েল-টাইম মিটিং ট্রান্সক্রিপশন। অ্যাকশন আইটেম ও সারসংক্ষেপ অটো।",
    review_bn: "ক্লায়েন্ট কল রেকর্ড করি। পরে মিনিটস বানাতে কোনো সময় লাগে না।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.3,
    direct_url: "https://otter.ai",
    affiliate_url: "https://otter.ai",
    pricing_url: "https://otter.ai",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-01-01",
    bestFor: ["মিটিং ট্রান্সক্রিপশন", "ক্লায়েন্ট কল", "নোট"],
    difficultyLevel: "সহজ",
    tags: ["transcription", "meeting", "free"],
    similarTools: ["descript", "notebooklm"],
  },
  {
    name: "Zapier",
    logo: "https://logo.clearbit.com/zapier.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=zapier.com&sz=64",
    category: "productivity",
    pricing: "freemium",
    usdPrice: "Free (100 tasks) / $29.99/mo (Professional) / $103.50/mo (Team)",
    verified: "মার্চ ২০২৬",
    details: "Free tier with 100 tasks/mo. Professional $29.99/mo for 750 tasks. Team $103.50/mo for 2,000 tasks. Enterprise custom pricing.",
    description_bn: "৬০০০+ অ্যাপের মধ্যে AI-পাওয়ার্ড অটোমেশন। কোড ছাড়াই ওয়ার্কফ্লো।",
    review_bn: "Gmail থেকে Notion-এ অটো ডেটা যায়। ৩ ঘন্টার কাজ ০ মিনিটে!",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.5,
    direct_url: "https://zapier.com",
    affiliate_url: "https://zapier.com/affiliate",
    pricing_url: "https://zapier.com/pricing",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-01-01",
    bestFor: ["অটোমেশন", "ওয়ার্কফ্লো", "ইন্টিগ্রেশন", "নো-কোড"],
    difficultyLevel: "মধ্যম",
    tags: ["automation", "workflow", "no-code", "free"],
    similarTools: ["make", "notion-ai"],
  },
  {
    name: "Make",
    logo: "https://logo.clearbit.com/make.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=make.com&sz=64",
    category: "productivity",
    pricing: "freemium",
    usdPrice: "Free (1,000 ops) / $10.59/mo (Core) / $18.82/mo (Pro)",
    verified: "মার্চ ২০২৬",
    details: "Free tier with 1,000 operations/mo. Core $10.59/mo for 10,000 ops. More cost-effective than Zapier at scale.",
    description_bn: "ভিজ্যুয়াল অটোমেশন প্ল্যাটফর্ম। AI-পাওয়ার্ড ওয়ার্কফ্লো ড্র্যাগ-অ্যান্ড-ড্রপে।",
    review_bn: "Zapier-এর চেয়ে সস্তা এবং আরও ফ্লেক্সিবল।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.5,
    direct_url: "https://www.make.com",
    affiliate_url: "https://www.make.com/en/affiliate-program",
    pricing_url: "https://www.make.com/en/pricing",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: false,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-01-01",
    bestFor: ["অটোমেশন", "ওয়ার্কফ্লো", "Zapier বিকল্প"],
    difficultyLevel: "মধ্যম",
    tags: ["automation", "workflow", "free"],
    similarTools: ["zapier", "notion-ai"],
  },
  {
    name: "Jasper AI",
    logo: "https://logo.clearbit.com/jasper.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=jasper.ai&sz=64",
    category: "productivity",
    pricing: "paid",
    usdPrice: "$59-69/mo (Pro) / Custom (Business)",
    verified: "মার্চ ২০২৬",
    details: "Pro plan $59/mo (annual) or $69/mo (monthly). Business plan custom pricing. 7-day free trial. AI marketing content platform.",
    description_bn: "মার্কেটিং টিমের জন্য AI কন্টেন্ট প্ল্যাটফর্ম। ব্লগ, বিজ্ঞাপন, ইমেইল স্কেলে।",
    review_bn: "ইংরেজি কন্টেন্ট মার্কেটিংয়ে ROI অনেক ভালো।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.2,
    direct_url: "https://www.jasper.ai",
    affiliate_url: "https://www.jasper.ai/affiliates",
    pricing_url: "https://www.jasper.ai/pricing",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: false,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-01-01",
    bestFor: ["মার্কেটিং কন্টেন্ট", "ব্লগ", "বিজ্ঞাপন", "ইমেইল"],
    difficultyLevel: "সহজ",
    tags: ["writing", "marketing", "content"],
    similarTools: ["chatgpt", "notion-ai", "gamma"],
  },
  {
    name: "NotebookLM",
    logo: "https://logo.clearbit.com/notebooklm.google.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=notebooklm.google.com&sz=64",
    category: "productivity",
    pricing: "free",
    usdPrice: "সম্পূর্ণ ফ্রি",
    verified: "মার্চ ২০২৬",
    description_bn: "Google-এর ফ্রি AI — PDF আপলোড করুন, সাথে সাথে প্রশ্ন করুন, অডিও সারসংক্ষেপ পান",
    review_bn: "পরীক্ষার আগে বইয়ের PDF দিয়ে NotebookLM-এ প্রশ্ন করি — অসাধারণ কাজ করে।",
    works_in_bd: true, no_vpn: true, payment: "free", rating: 4.7,
    direct_url: "https://notebooklm.google.com",
    affiliate_url: "https://notebooklm.google.com",
    pricing_url: "https://notebooklm.google.com",
    // Enhanced schema
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2024-06-01",
    bestFor: ["PDF বিশ্লেষণ", "স্টাডি", "রিসার্চ", "অডিও সারসংক্ষেপ"],
    difficultyLevel: "সহজ",
    tags: ["research", "pdf", "free", "google"],
    similarTools: ["perplexity-ai", "chatgpt", "claude"],
  },

  // ── Batch 1: Video & Voice Tools ────────────────────────────────────────
  {
    name: "HeyGen",
    logo: "https://logo.clearbit.com/heygen.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=heygen.com&sz=64",
    category: "productivity",
    pricing: "ফ্রি / ৳৩,৫৩৮",
    usdPrice: 29,
    verified: "মার্চ ২০২৬",
    description_bn: "AI অবতার দিয়ে প্রফেশনাল মার্কেটিং ভিডিও তৈরি করুন — ক্যামেরার সামনে না গিয়েই। ১০০+ ভাষায় ভয়েস ক্লোনিং সাপোর্ট।",
    review_bn: "ক্যামেরার সামনে না গিয়ে প্রফেশনাল ভিডিও বানাতে পারছি — বাংলাদেশের ব্যবসার জন্য গেমচেঞ্জার।",
    works_in_bd: true, no_vpn: true, payment: ["card", "wise"], rating: 4.6,
    direct_url: "https://www.heygen.com",
    affiliate_url: "",
    pricing_url: "https://www.heygen.com/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: true,
    dateAdded: "2026-03-27",
    bestFor: ["AI অবতার ভিডিও", "মার্কেটিং ভিডিও", "ভয়েস ক্লোন", "ট্রেনিং ভিডিও"],
    difficultyLevel: "সহজ",
    tags: ["video", "avatar", "voice", "marketing"],
    similarTools: ["synthesia", "d-id", "runway-ml"],
  },
  {
    name: "Synthesia",
    logo: "https://logo.clearbit.com/synthesia.io",
    logo_fallback: "https://www.google.com/s2/favicons?domain=synthesia.io&sz=64",
    category: "productivity",
    pricing: "ফ্রি / ৳২,১৯৬",
    usdPrice: 18,
    verified: "মার্চ ২০২৬",
    description_bn: "AI অবতার ও ভয়েস দিয়ে কর্পোরেট ট্রেনিং ভিডিও ও মার্কেটিং কন্টেন্ট তৈরি করুন — ১৩০+ ভাষায়।",
    review_bn: "টিম ট্রেনিং ভিডিও বানাতে Synthesia সবচেয়ে ভালো — একবার বানালেই বারবার কাজে লাগে।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.5,
    direct_url: "https://www.synthesia.io",
    affiliate_url: "",
    pricing_url: "https://www.synthesia.io/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-27",
    bestFor: ["ট্রেনিং ভিডিও", "AI অবতার", "কর্পোরেট কন্টেন্ট", "মাল্টিলিঙ্গুয়াল ভিডিও"],
    difficultyLevel: "সহজ",
    tags: ["video", "avatar", "corporate", "training"],
    similarTools: ["heygen", "d-id", "invideo-ai"],
  },
  {
    name: "D-ID",
    logo: "https://logo.clearbit.com/d-id.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=d-id.com&sz=64",
    category: "productivity",
    pricing: "ফ্রি / ৳৭২০",
    usdPrice: 5.9,
    verified: "মার্চ ২০২৬",
    description_bn: "ছবি থেকে কথা বলানো AI ভিডিও তৈরি করুন — যেকোনো ছবিকে জীবন্ত অবতারে পরিণত করুন ভয়েস ও অ্যানিমেশনসহ।",
    review_bn: "মাত্র একটা ছবি দিয়ে পুরো ভিডিও প্রেজেন্টেশন বানিয়ে ফেলা যায় — অবিশ্বাস্য।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.3,
    direct_url: "https://www.d-id.com",
    affiliate_url: "",
    pricing_url: "https://www.d-id.com/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-27",
    bestFor: ["ফটো অ্যানিমেশন", "AI অবতার", "ভিডিও প্রেজেন্টেশন", "সোশ্যাল মিডিয়া"],
    difficultyLevel: "সহজ",
    tags: ["video", "avatar", "animation", "photo"],
    similarTools: ["heygen", "synthesia", "runway-ml"],
  },
  {
    name: "Opus Clip",
    logo: "https://logo.clearbit.com/opus.pro",
    logo_fallback: "https://www.google.com/s2/favicons?domain=opus.pro&sz=64",
    category: "productivity",
    pricing: "ফ্রি / ৳১,৮৩০",
    usdPrice: 15,
    verified: "মার্চ ২০২৬",
    description_bn: "লং ভিডিও থেকে AI দিয়ে ভাইরাল শর্ট ক্লিপ বানান — YouTube, Facebook ও TikTok-এর জন্য অটোমেটিক ক্যাপশনসহ।",
    review_bn: "এক ঘণ্টার ভিডিও থেকে ৫টা ভাইরাল ক্লিপ বের করে দেয় — কন্টেন্ট ক্রিয়েটরদের জন্য মাস্ট।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.5,
    direct_url: "https://www.opus.pro",
    affiliate_url: "",
    pricing_url: "https://www.opus.pro/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-27",
    bestFor: ["শর্ট ভিডিও", "YouTube Shorts", "ভাইরাল ক্লিপ", "পডকাস্ট ক্লিপ"],
    difficultyLevel: "সহজ",
    tags: ["video", "short-form", "repurpose", "youtube"],
    similarTools: ["capcut-ai", "descript", "invideo-ai"],
  },
  {
    name: "Murf AI",
    logo: "https://logo.clearbit.com/murf.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=murf.ai&sz=64",
    category: "productivity",
    pricing: "ফ্রি / ৳২,৩১৮",
    usdPrice: 19,
    verified: "মার্চ ২০২৬",
    description_bn: "প্রফেশনাল AI ভয়েসওভার তৈরি করুন — ১২০+ ভাষায়, ২০০+ কণ্ঠ। পডকাস্ট, বিজ্ঞাপন ও অডিওবুকের জন্য।",
    review_bn: "বিজ্ঞাপনের ভয়েসওভার এখন নিজেই বানাই — স্টুডিওর খরচ বেঁচে যায়।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.5,
    direct_url: "https://murf.ai",
    affiliate_url: "",
    pricing_url: "https://murf.ai/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-27",
    bestFor: ["ভয়েসওভার", "পডকাস্ট", "অডিওবুক", "ই-লার্নিং"],
    difficultyLevel: "সহজ",
    tags: ["voice", "audio", "voiceover", "tts"],
    similarTools: ["elevenlabs", "play-ht", "adobe-podcast"],
  },
  {
    name: "PlayHT",
    logo: "https://logo.clearbit.com/play.ht",
    logo_fallback: "https://www.google.com/s2/favicons?domain=play.ht&sz=64",
    category: "productivity",
    pricing: "ফ্রি / ৳৩,৮০৬",
    usdPrice: 31.2,
    verified: "মার্চ ২০২৬",
    description_bn: "অতি বাস্তবসম্মত AI ভয়েস ক্লোনিং ও টেক্সট-টু-স্পিচ — আপনার নিজের কণ্ঠ ক্লোন করুন মাত্র ৩০ সেকেন্ডের অডিওতে।",
    review_bn: "নিজের ভয়েস ক্লোন করে পডকাস্ট বানাচ্ছি — শুনলে পার্থক্য বোঝাই যায় না।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.4,
    direct_url: "https://play.ht",
    affiliate_url: "",
    pricing_url: "https://play.ht/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-27",
    bestFor: ["ভয়েস ক্লোন", "পডকাস্ট", "টেক্সট-টু-স্পিচ", "কন্টেন্ট"],
    difficultyLevel: "মাঝারি",
    tags: ["voice", "audio", "clone", "tts"],
    similarTools: ["elevenlabs", "murf-ai", "descript"],
  },
  {
    name: "InVideo AI",
    logo: "https://logo.clearbit.com/invideo.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=invideo.ai&sz=64",
    category: "productivity",
    pricing: "ফ্রি / ৳২,৪৪০",
    usdPrice: 20,
    verified: "মার্চ ২০২৬",
    description_bn: "টেক্সট বা আইডিয়া থেকে সম্পূর্ণ মার্কেটিং ভিডিও তৈরি করুন — স্ক্রিপ্ট, ভয়েস ও ভিজ্যুয়াল সব AI-তে।",
    review_bn: "প্রমোশনাল ভিডিও বানাতে এখন ৩০ মিনিটের বেশি লাগে না — অবিশ্বাস্য সহজ।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.4,
    direct_url: "https://invideo.io",
    affiliate_url: "",
    pricing_url: "https://invideo.io/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-27",
    bestFor: ["মার্কেটিং ভিডিও", "সোশ্যাল মিডিয়া", "প্রমোশনাল কন্টেন্ট", "YouTube"],
    difficultyLevel: "সহজ",
    tags: ["video", "marketing", "social-media", "ai-video"],
    similarTools: ["heygen", "pictory", "opus-clip"],
  },
  {
    name: "Pictory",
    logo: "https://logo.clearbit.com/pictory.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=pictory.ai&sz=64",
    category: "productivity",
    pricing: "৳২,৩১৮",
    usdPrice: 19,
    verified: "মার্চ ২০২৬",
    description_bn: "ব্লগ পোস্ট বা স্ক্রিপ্ট থেকে অটোমেটিক ভিডিও বানান — AI ক্যাপশন ও স্টক ফুটেজ সহ।",
    review_bn: "আর্টিকেল থেকে ভিডিও বানাতে Pictory সেরা — SEO ও সোশ্যাল মিডিয়া দুটোতেই কাজে লাগে।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.3,
    direct_url: "https://pictory.ai",
    affiliate_url: "",
    pricing_url: "https://pictory.ai/pricing",
    supportsBangla: false,
    freePlanAvailable: false,
    mobileFriendly: false,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-27",
    bestFor: ["ব্লগ-টু-ভিডিও", "সোশ্যাল মিডিয়া", "AI ক্যাপশন", "কন্টেন্ট রিপার্পাজিং"],
    difficultyLevel: "সহজ",
    tags: ["video", "repurpose", "blog", "captions"],
    similarTools: ["invideo-ai", "opus-clip", "descript"],
  },
  {
    name: "Fliki",
    logo: "https://logo.clearbit.com/fliki.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=fliki.ai&sz=64",
    category: "productivity",
    pricing: "ফ্রি / ৳২,৫৬২",
    usdPrice: 21,
    verified: "মার্চ ২০২৬",
    description_bn: "টেক্সট থেকে AI ভিডিও ও পডকাস্ট তৈরি করুন — ৭৫+ ভাষায় ৯০০+ রিয়েলিস্টিক ভয়েস।",
    review_bn: "বাংলায় টেক্সট দিলে ইংরেজি ভয়েসে ভিডিও বানিয়ে দেয় — কন্টেন্ট মার্কেটারদের সময় বাঁচায়।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.3,
    direct_url: "https://fliki.ai",
    affiliate_url: "",
    pricing_url: "https://fliki.ai/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-27",
    bestFor: ["ভিডিও কন্টেন্ট", "পডকাস্ট", "সোশ্যাল মিডিয়া", "টেক্সট-টু-ভিডিও"],
    difficultyLevel: "সহজ",
    tags: ["video", "voice", "podcast", "tts"],
    similarTools: ["invideo-ai", "murf-ai", "pictory"],
  },
  {
    name: "CapCut AI",
    logo: "https://logo.clearbit.com/capcut.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=capcut.com&sz=64",
    category: "productivity",
    pricing: "ফ্রি / ৳৭৩২",
    usdPrice: 6,
    verified: "মার্চ ২০২৬",
    description_bn: "বাংলাদেশে সবচেয়ে জনপ্রিয় ভিডিও এডিটিং অ্যাপ — AI ক্যাপশন, ব্যাকগ্রাউন্ড রিমুভাল ও অটো সাবটাইটেল ফিচার।",
    review_bn: "ফোনেই প্রফেশনাল ভিডিও বানাই — AI ফিচারগুলো সত্যিই কাজের।",
    works_in_bd: true, no_vpn: true, payment: ["card", "free"], rating: 4.7,
    direct_url: "https://www.capcut.com",
    affiliate_url: "",
    pricing_url: "https://www.capcut.com/pricing",
    supportsBangla: true,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: true,
    dateAdded: "2026-03-27",
    bestFor: ["ভিডিও এডিটিং", "রিলস", "শর্টস", "AI সাবটাইটেল"],
    difficultyLevel: "সহজ",
    tags: ["video", "editing", "mobile", "free"],
    similarTools: ["opus-clip", "descript", "invideo-ai"],
  },
  {
    name: "Loom AI",
    logo: "https://logo.clearbit.com/loom.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=loom.com&sz=64",
    category: "productivity",
    pricing: "ফ্রি / ৳১,৫২৫",
    usdPrice: 12.5,
    verified: "মার্চ ২০২৬",
    description_bn: "স্ক্রিন রেকর্ড করুন এবং AI দিয়ে অটোমেটিক সারসংক্ষেপ, চ্যাপ্টার ও অ্যাকশন আইটেম পান — টিম কমিউনিকেশনের জন্য।",
    review_bn: "মিটিং না করে Loom ভিডিও পাঠাই — টিমের সাথে যোগাযোগ অনেক সহজ হয়ে গেছে।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.5,
    direct_url: "https://www.loom.com",
    affiliate_url: "",
    pricing_url: "https://www.loom.com/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-27",
    bestFor: ["স্ক্রিন রেকর্ডিং", "টিম কমিউনিকেশন", "ভিডিও মেসেজিং", "ট্রেনিং"],
    difficultyLevel: "সহজ",
    tags: ["video", "screen-recording", "team", "communication"],
    similarTools: ["otter-ai", "descript", "notion-ai"],
  },
  {
    name: "Adobe Podcast",
    logo: "https://logo.clearbit.com/podcast.adobe.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=adobe.com&sz=64",
    category: "productivity",
    pricing: "ফ্রি",
    usdPrice: 0,
    verified: "মার্চ ২০২৬",
    description_bn: "Adobe-এর ফ্রি AI অডিও টুল — যেকোনো জায়গা থেকে রেকর্ড করা পডকাস্টকে স্টুডিও মানের অডিওতে রূপান্তর করে।",
    review_bn: "বাড়িতে রেকর্ড করা পডকাস্টের নয়েজ ম্যাজিকের মতো চলে যায় — সম্পূর্ণ ফ্রি।",
    works_in_bd: true, no_vpn: true, payment: ["free"], rating: 4.6,
    direct_url: "https://podcast.adobe.com",
    affiliate_url: "",
    pricing_url: "https://podcast.adobe.com",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-27",
    bestFor: ["পডকাস্ট", "অডিও ক্লিনআপ", "নয়েজ রিমুভাল", "ভয়েস এনহান্সমেন্ট"],
    difficultyLevel: "সহজ",
    tags: ["audio", "podcast", "voice", "free"],
    similarTools: ["murf-ai", "elevenlabs", "descript"],
  },

  // ── Batch 2: Marketing & SEO Tools ──────────────────────────────────────
  {
    name: "Copy.ai",
    logo: "https://logo.clearbit.com/copy.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=copy.ai&sz=64",
    category: "productivity",
    pricing: "ফ্রি / ৳৪,৩৯২",
    usdPrice: 36,
    verified: "মার্চ ২০২৬",
    description_bn: "AI মার্কেটিং কন্টেন্ট রাইটার — বিজ্ঞাপন কপি, ইমেইল ক্যাম্পেইন, ব্লগ পোস্ট ও সোশ্যাল মিডিয়া ক্যাপশন সেকেন্ডে।",
    review_bn: "ফেসবুক বিজ্ঞাপনের কপি লিখতে ঘণ্টার পর ঘণ্টা লাগত — Copy.ai-তে এখন ২ মিনিট।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.4,
    direct_url: "https://www.copy.ai",
    affiliate_url: "",
    pricing_url: "https://www.copy.ai/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-27",
    bestFor: ["বিজ্ঞাপন কপি", "ইমেইল মার্কেটিং", "ক্যাম্পেইন", "সোশ্যাল মিডিয়া"],
    difficultyLevel: "সহজ",
    tags: ["marketing", "copywriting", "ads", "email campaign"],
    similarTools: ["jasper-ai", "writesonic", "rytr"],
  },
  {
    name: "Writesonic",
    logo: "https://logo.clearbit.com/writesonic.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=writesonic.com&sz=64",
    category: "productivity",
    pricing: "ফ্রি / ৳১,৯৫২",
    usdPrice: 16,
    verified: "মার্চ ২০২৬",
    description_bn: "SEO-অপ্টিমাইজড ব্লগ পোস্ট ও মার্কেটিং কপি লিখুন AI দিয়ে — Google-র‌্যাংকিং উপযোগী কন্টেন্ট মিনিটে।",
    review_bn: "SEO ব্লগ লেখায় Writesonic অনেক কাজে লাগে — বাংলাদেশের কন্টেন্ট মার্কেটারদের জন্য ভালো।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.3,
    direct_url: "https://writesonic.com",
    affiliate_url: "",
    pricing_url: "https://writesonic.com/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-27",
    bestFor: ["SEO কন্টেন্ট", "ব্লগ পোস্ট", "মার্কেটিং", "ল্যান্ডিং পেজ"],
    difficultyLevel: "সহজ",
    tags: ["marketing", "seo", "content platform", "blog"],
    similarTools: ["copy-ai", "jasper-ai", "rytr"],
  },
  {
    name: "Rytr",
    logo: "https://logo.clearbit.com/rytr.me",
    logo_fallback: "https://www.google.com/s2/favicons?domain=rytr.me&sz=64",
    category: "productivity",
    pricing: "ফ্রি / ৳১,০৯৮",
    usdPrice: 9,
    verified: "মার্চ ২০২৬",
    description_bn: "সাশ্রয়ী AI রাইটিং টুল — মার্কেটিং কপি, ইমেইল ও ব্লগ ফ্রি প্ল্যানেই লেখা যায়। বাংলাদেশের ফ্রিল্যান্সারদের জন্য সেরা।",
    review_bn: "ফ্রি প্ল্যানেই অনেক কিছু করা যায় — ফ্রিল্যান্স রাইটারদের জন্য পারফেক্ট।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.2,
    direct_url: "https://rytr.me",
    affiliate_url: "",
    pricing_url: "https://rytr.me/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-27",
    bestFor: ["ফ্রিল্যান্স রাইটিং", "মার্কেটিং কপি", "ইমেইল", "বাজেট-বান্ধব"],
    difficultyLevel: "সহজ",
    tags: ["marketing", "writing", "email campaign", "affordable"],
    similarTools: ["copy-ai", "writesonic", "jasper-ai"],
  },
  {
    name: "Surfer SEO",
    logo: "https://logo.clearbit.com/surferseo.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=surferseo.com&sz=64",
    category: "productivity",
    pricing: "৳১০,৮৫৮",
    usdPrice: 89,
    verified: "মার্চ ২০২৬",
    description_bn: "AI-চালিত SEO কন্টেন্ট অপ্টিমাইজার — Google-এ র‌্যাংক করতে সঠিক কীওয়ার্ড, স্ট্রাকচার ও NLP স্কোর দেখায়।",
    review_bn: "Surfer ছাড়া এখন SEO আর্টিকেল লিখি না — র‌্যাংকিং অনেক দ্রুত হয়।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.5,
    direct_url: "https://surferseo.com",
    affiliate_url: "",
    pricing_url: "https://surferseo.com/pricing",
    supportsBangla: false,
    freePlanAvailable: false,
    mobileFriendly: false,
    beginnerFriendly: false,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-27",
    bestFor: ["SEO অপ্টিমাইজেশন", "কন্টেন্ট মার্কেটিং", "কীওয়ার্ড রিসার্চ", "র‌্যাংকিং"],
    difficultyLevel: "মাঝারি",
    tags: ["seo", "marketing", "content platform", "ranking"],
    similarTools: ["writesonic", "jasper-ai", "copy-ai"],
  },
  {
    name: "Buffer AI",
    logo: "https://logo.clearbit.com/buffer.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=buffer.com&sz=64",
    category: "productivity",
    pricing: "ফ্রি / ৳৭৩২",
    usdPrice: 6,
    verified: "মার্চ ২০২৬",
    description_bn: "সোশ্যাল মিডিয়া মার্কেটিং অটোমেশন — AI দিয়ে পোস্ট লিখুন, শিডিউল করুন ও Facebook, Instagram, LinkedIn ম্যানেজ করুন।",
    review_bn: "একসাথে সব সোশ্যাল মিডিয়া ম্যানেজ করতে Buffer ব্যবহার করি — মার্কেটিং অনেক সহজ।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.3,
    direct_url: "https://buffer.com",
    affiliate_url: "",
    pricing_url: "https://buffer.com/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-27",
    bestFor: ["সোশ্যাল মিডিয়া মার্কেটিং", "পোস্ট শিডিউল", "ক্যাম্পেইন", "অটোমেশন"],
    difficultyLevel: "সহজ",
    tags: ["marketing", "social-media", "scheduling", "campaign"],
    similarTools: ["zapier", "make", "jasper-ai"],
  },
  {
    name: "Canva Magic Write",
    logo: "https://logo.clearbit.com/canva.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=canva.com&sz=64",
    category: "productivity",
    pricing: "ফ্রি / ৳১,৪৬৪",
    usdPrice: 12,
    verified: "মার্চ ২০২৬",
    description_bn: "Canva-র AI রাইটিং ও ডিজাইন টুল — মার্কেটিং পোস্টার, সোশ্যাল মিডিয়া গ্রাফিক ও বিজ্ঞাপন কপি একসাথে।",
    review_bn: "ডিজাইন করতে করতে কপিও লিখতে পারি — ছোট ব্যবসার জন্য দারুণ।",
    works_in_bd: true, no_vpn: true, payment: ["card", "free"], rating: 4.6,
    direct_url: "https://www.canva.com",
    affiliate_url: "",
    pricing_url: "https://www.canva.com/pricing",
    supportsBangla: true,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: true,
    dateAdded: "2026-03-27",
    bestFor: ["মার্কেটিং গ্রাফিক", "সোশ্যাল মিডিয়া পোস্ট", "বিজ্ঞাপন", "প্রেজেন্টেশন"],
    difficultyLevel: "সহজ",
    tags: ["marketing", "design", "social-media", "ads"],
    similarTools: ["adobe-firefly", "ideogram", "gamma"],
  },

  // ── Batch 3: Design & Image Tools ───────────────────────────────────────
  {
    name: "Remove.bg",
    logo: "https://logo.clearbit.com/remove.bg",
    logo_fallback: "https://www.google.com/s2/favicons?domain=remove.bg&sz=64",
    category: "image",
    pricing: "ফ্রি / ৳১,০৯৮",
    usdPrice: 9,
    verified: "মার্চ ২০২৬",
    description_bn: "এক ক্লিকে ছবির ব্যাকগ্রাউন্ড রিমুভ করুন — পণ্যের ছবি, প্রোফাইল ফটো ও ই-কমার্সের জন্য বাংলাদেশে সবচেয়ে বেশি ব্যবহৃত।",
    review_bn: "আমার পণ্যের ব্যাকগ্রাউন্ড সরাতে ফটোশপ লাগত না — Remove.bg-তে এক সেকেন্ড।",
    works_in_bd: true, no_vpn: true, payment: ["card", "free"], rating: 4.7,
    direct_url: "https://www.remove.bg",
    affiliate_url: "",
    pricing_url: "https://www.remove.bg/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: true,
    dateAdded: "2026-03-27",
    bestFor: ["ব্যাকগ্রাউন্ড রিমুভাল", "পণ্যের ছবি", "ই-কমার্স", "প্রোফাইল ফটো"],
    difficultyLevel: "সহজ",
    tags: ["image", "background-removal", "ecommerce", "free"],
    similarTools: ["adobe-firefly", "clipdrop", "canva-magic-write"],
  },
  {
    name: "Clipdrop",
    logo: "https://logo.clearbit.com/clipdrop.co",
    logo_fallback: "https://www.google.com/s2/favicons?domain=clipdrop.co&sz=64",
    category: "image",
    pricing: "ফ্রি / ৳৮৫৪",
    usdPrice: 7,
    verified: "মার্চ ২০২৬",
    description_bn: "Stability AI-র ইমেজ এডিটিং টুল — ব্যাকগ্রাউন্ড রিমুভ, আনক্লিপ, রিলাইট ও আনব্লার সব AI দিয়ে।",
    review_bn: "ছবি এডিট করতে এখন Photoshop খুলতে হয় না — Clipdrop-এই সব কাজ হয়।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.4,
    direct_url: "https://clipdrop.co",
    affiliate_url: "",
    pricing_url: "https://clipdrop.co/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-27",
    bestFor: ["ইমেজ এডিটিং", "ব্যাকগ্রাউন্ড রিমুভাল", "ফটো রিটাচিং", "AI আর্ট"],
    difficultyLevel: "সহজ",
    tags: ["image", "editing", "background-removal", "ai-art"],
    similarTools: ["remove-bg", "adobe-firefly", "stable-diffusion"],
  },
  {
    name: "Pika Labs",
    logo: "https://logo.clearbit.com/pika.art",
    logo_fallback: "https://www.google.com/s2/favicons?domain=pika.art&sz=64",
    category: "image",
    pricing: "ফ্রি / ৳৯৭৬",
    usdPrice: 8,
    verified: "মার্চ ২০২৬",
    description_bn: "টেক্সট বা ছবি থেকে সুন্দর AI ভিডিও ক্লিপ তৈরি করুন — সোশ্যাল মিডিয়া ও বিজ্ঞাপনের জন্য।",
    review_bn: "ছবি থেকে অ্যানিমেটেড ভিডিও বানাতে Pika অসাধারণ — ফ্রি প্ল্যানেও বেশ ভালো।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.3,
    direct_url: "https://pika.art",
    affiliate_url: "",
    pricing_url: "https://pika.art/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-27",
    bestFor: ["AI ভিডিও", "ইমেজ-টু-ভিডিও", "সোশ্যাল মিডিয়া", "অ্যানিমেশন"],
    difficultyLevel: "সহজ",
    tags: ["image", "video", "animation", "text-to-video"],
    similarTools: ["runway-ml", "kling-ai", "flux"],
  },
  {
    name: "Looka",
    logo: "https://logo.clearbit.com/looka.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=looka.com&sz=64",
    category: "image",
    pricing: "৳২,৪৪০",
    usdPrice: 20,
    verified: "মার্চ ২০২৬",
    description_bn: "AI দিয়ে ব্যবসার লোগো, ব্র্যান্ড কিট ও ভিজিটিং কার্ড ডিজাইন করুন — ডিজাইনার ছাড়াই প্রফেশনাল ব্র্যান্ড পরিচয় তৈরি।",
    review_bn: "মাত্র ৫ মিনিটে পুরো ব্র্যান্ড কিট তৈরি হয়ে গেল — স্টার্টআপের জন্য পারফেক্ট।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.3,
    direct_url: "https://looka.com",
    affiliate_url: "",
    pricing_url: "https://looka.com/pricing",
    supportsBangla: false,
    freePlanAvailable: false,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-27",
    bestFor: ["লোগো ডিজাইন", "ব্র্যান্ড কিট", "স্টার্টআপ", "ব্যবসা"],
    difficultyLevel: "সহজ",
    tags: ["image", "logo", "branding", "design"],
    similarTools: ["canva-magic-write", "adobe-firefly", "ideogram"],
  },

  // ── Batch 4: Coding & Dev Tools ──────────────────────────────────────────
  {
    name: "Tabnine",
    logo: "https://logo.clearbit.com/tabnine.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=tabnine.com&sz=64",
    category: "coding",
    pricing: "ফ্রি / ৳১,৪৬৪",
    usdPrice: 12,
    verified: "মার্চ ২০২৬",
    description_bn: "প্রাইভেসি-ফার্স্ট AI কোড কমপ্লিশন — আপনার কোডবেস থেকে শিখে পর্সোনালাইজড সাজেশন দেয়, কোড কখনো সার্ভারে যায় না।",
    review_bn: "প্রাইভেট কোড নিয়ে চিন্তা নেই — Tabnine সব লোকালি রাখে।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.3,
    direct_url: "https://www.tabnine.com",
    affiliate_url: "",
    pricing_url: "https://www.tabnine.com/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: false,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-27",
    bestFor: ["কোড কমপ্লিশন", "প্রাইভেট কোড", "VS Code", "এন্টারপ্রাইজ"],
    difficultyLevel: "মাঝারি",
    tags: ["coding", "autocomplete", "privacy", "vscode"],
    similarTools: ["github-copilot", "codeium", "cursor"],
  },
  {
    name: "Codeium",
    logo: "https://logo.clearbit.com/codeium.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=codeium.com&sz=64",
    category: "coding",
    pricing: "সম্পূর্ণ ফ্রি",
    usdPrice: 0,
    verified: "মার্চ ২০২৬",
    description_bn: "সম্পূর্ণ ফ্রি AI কোড অ্যাসিস্ট্যান্ট — GitHub Copilot-এর বিকল্প। ৭০+ প্রোগ্রামিং ল্যাঙ্গুয়েজ সাপোর্ট, কোনো ক্রেডিট কার্ড লাগে না।",
    review_bn: "GitHub Copilot-এর মতো কিন্তু সম্পূর্ণ ফ্রি — বাংলাদেশের ডেভেলপারদের জন্য সেরা।",
    works_in_bd: true, no_vpn: true, payment: ["free"], rating: 4.5,
    direct_url: "https://codeium.com",
    affiliate_url: "",
    pricing_url: "https://codeium.com/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: true,
    dateAdded: "2026-03-27",
    bestFor: ["ফ্রি কোডিং AI", "কোড কমপ্লিশন", "নতুন ডেভেলপার", "স্টুডেন্ট"],
    difficultyLevel: "সহজ",
    tags: ["coding", "free", "autocomplete", "copilot-alternative"],
    similarTools: ["github-copilot", "tabnine", "cursor"],
  },
  {
    name: "Phind",
    logo: "https://logo.clearbit.com/phind.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=phind.com&sz=64",
    category: "coding",
    pricing: "ফ্রি / ৳২,১৯৬",
    usdPrice: 18,
    verified: "মার্চ ২০২৬",
    description_bn: "ডেভেলপারদের জন্য AI সার্চ ইঞ্জিন — Stack Overflow না খুঁজে সরাসরি কোডিং সমস্যার সমাধান পান সোর্স সহ।",
    review_bn: "বাগ ফিক্স করতে এখন Phind ব্যবহার করি — Stack Overflow-এর চেয়ে অনেক দ্রুত।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.5,
    direct_url: "https://www.phind.com",
    affiliate_url: "",
    pricing_url: "https://www.phind.com/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-27",
    bestFor: ["কোডিং সার্চ", "ডিবাগিং", "ডকুমেন্টেশন", "ডেভেলপার"],
    difficultyLevel: "সহজ",
    tags: ["coding", "search", "debugging", "developer"],
    similarTools: ["perplexity-ai", "cursor", "github-copilot"],
  },
  {
    name: "Warp AI",
    logo: "https://logo.clearbit.com/warp.dev",
    logo_fallback: "https://www.google.com/s2/favicons?domain=warp.dev&sz=64",
    category: "coding",
    pricing: "ফ্রি / ৳১,৪৬৪",
    usdPrice: 12,
    verified: "মার্চ ২০২৬",
    description_bn: "AI-চালিত টার্মিনাল — কমান্ড ভুলে গেলে বাংলায় বা ইংরেজিতে বলুন, Warp নিজেই কমান্ড লিখে দেবে।",
    review_bn: "টার্মিনাল কমান্ড মনে না থাকলেও সমস্যা নেই — Warp বলে দেয়।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.4,
    direct_url: "https://www.warp.dev",
    affiliate_url: "",
    pricing_url: "https://www.warp.dev/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: false,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-27",
    bestFor: ["AI টার্মিনাল", "DevOps", "ব্যাশ কমান্ড", "ডেভেলপার"],
    difficultyLevel: "মাঝারি",
    tags: ["coding", "terminal", "devops", "cli"],
    similarTools: ["cursor", "github-copilot", "claude-code"],
  },

  // ── Batch 5: Research, LLM & Productivity ────────────────────────────────
  {
    name: "Microsoft Copilot",
    logo: "https://logo.clearbit.com/copilot.microsoft.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=microsoft.com&sz=64",
    category: "llm",
    pricing: "ফ্রি / ৳২,৪৪০",
    usdPrice: 20,
    verified: "মার্চ ২০২৬",
    description_bn: "Microsoft-এর GPT-4 চালিত ফ্রি AI — Bing সার্চ, Word, Excel ও Teams-এ সরাসরি ব্যবহার করুন। বাংলাদেশে VPN ছাড়া কাজ করে।",
    review_bn: "Office-এ কাজ করতে করতে AI হেল্প পাই — আলাদা ট্যাব খুলতে হয় না।",
    works_in_bd: true, no_vpn: true, payment: ["free", "card"], rating: 4.4,
    direct_url: "https://copilot.microsoft.com",
    affiliate_url: "",
    pricing_url: "https://copilot.microsoft.com",
    supportsBangla: true,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: true,
    dateAdded: "2026-03-27",
    bestFor: ["Office সহায়তা", "ফ্রি GPT-4", "Bing সার্চ", "Word/Excel"],
    difficultyLevel: "সহজ",
    tags: ["llm", "free", "microsoft", "office"],
    similarTools: ["chatgpt", "gemini", "claude"],
  },
  {
    name: "You.com",
    logo: "https://logo.clearbit.com/you.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=you.com&sz=64",
    category: "llm",
    pricing: "ফ্রি / ৳২,০০৯",
    usdPrice: 16.49,
    verified: "মার্চ ২০২৬",
    description_bn: "AI সার্চ ইঞ্জিন ও চ্যাটবট — রিয়েল-টাইম ওয়েব অ্যাক্সেস সহ, GPT-4, Claude ও Gemini সব একসাথে ট্রাই করুন।",
    review_bn: "একটাই সাইটে বিভিন্ন AI মডেল তুলনা করা যায় — রিসার্চ করতে অনেক কাজের।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.3,
    direct_url: "https://you.com",
    affiliate_url: "",
    pricing_url: "https://you.com/plans",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-27",
    bestFor: ["AI সার্চ", "মডেল তুলনা", "রিসার্চ", "ওয়েব অ্যাক্সেস"],
    difficultyLevel: "সহজ",
    tags: ["llm", "search", "research", "multi-model"],
    similarTools: ["perplexity-ai", "chatgpt", "microsoft-copilot"],
  },
  {
    name: "Fireflies.ai",
    logo: "https://logo.clearbit.com/fireflies.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=fireflies.ai&sz=64",
    category: "productivity",
    pricing: "ফ্রি / ৳১,২২০",
    usdPrice: 10,
    verified: "মার্চ ২০২৬",
    description_bn: "AI মিটিং নোটস ও ট্রান্সক্রিপশন — Zoom, Google Meet ও Teams মিটিং অটো রেকর্ড করে সারসংক্ষেপ ও অ্যাকশন আইটেম দেয়।",
    review_bn: "মিটিং নোট নেওয়ার ঝামেলা শেষ — Fireflies সব ট্রান্সক্রাইব করে অ্যাকশন আইটেমও বলে দেয়।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.5,
    direct_url: "https://fireflies.ai",
    affiliate_url: "",
    pricing_url: "https://fireflies.ai/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-27",
    bestFor: ["মিটিং নোটস", "ট্রান্সক্রিপশন", "Zoom", "Google Meet"],
    difficultyLevel: "সহজ",
    tags: ["productivity", "meeting", "transcription", "audio"],
    similarTools: ["otter-ai", "notebooklm", "loom-ai"],
  },
  {
    name: "Taskade AI",
    logo: "https://logo.clearbit.com/taskade.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=taskade.com&sz=64",
    category: "productivity",
    pricing: "ফ্রি / ৳৯৭৬",
    usdPrice: 8,
    verified: "মার্চ ২০২৬",
    description_bn: "AI-চালিত প্রজেক্ট ম্যানেজমেন্ট ও টিম কোলাবোরেশন টুল — টাস্ক, নোটস, মাইন্ড ম্যাপ ও চ্যাট একসাথে।",
    review_bn: "ছোট টিমের জন্য Taskade ব্যবহার করি — AI দিয়ে প্রজেক্ট প্ল্যান বানানো সহজ।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.3,
    direct_url: "https://www.taskade.com",
    affiliate_url: "",
    pricing_url: "https://www.taskade.com/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-27",
    bestFor: ["প্রজেক্ট ম্যানেজমেন্ট", "টিম কোলাবোরেশন", "টাস্ক লিস্ট", "মাইন্ড ম্যাপ"],
    difficultyLevel: "সহজ",
    tags: ["productivity", "project-management", "team", "collaboration"],
    similarTools: ["notion-ai", "zapier", "make"],
  },
  {
    name: "Beautiful.ai",
    logo: "https://logo.clearbit.com/beautiful.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=beautiful.ai&sz=64",
    category: "productivity",
    pricing: "৳১,৪৬৪",
    usdPrice: 12,
    verified: "মার্চ ২০২৬",
    description_bn: "AI-চালিত প্রেজেন্টেশন মেকার — স্লাইড অটো-ডিজাইন হয়, কন্টেন্ট যোগ করলে লেআউট নিজেই সুন্দর হয়।",
    review_bn: "PowerPoint-এর ঝামেলা থেকে মুক্তি — Beautiful.ai-তে স্লাইড নিজেই সুন্দর দেখায়।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.3,
    direct_url: "https://www.beautiful.ai",
    affiliate_url: "",
    pricing_url: "https://www.beautiful.ai/pricing",
    supportsBangla: false,
    freePlanAvailable: false,
    mobileFriendly: false,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-27",
    bestFor: ["প্রেজেন্টেশন", "স্লাইড ডেক", "পিচ ডেক", "ব্যবসায়িক"],
    difficultyLevel: "সহজ",
    tags: ["productivity", "presentation", "slides", "design"],
    similarTools: ["gamma", "canva-magic-write", "notion-ai"],
  },
  {
    name: "Elicit",
    logo: "https://logo.clearbit.com/elicit.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=elicit.com&sz=64",
    category: "llm",
    pricing: "ফ্রি / ৳১,২২০",
    usdPrice: 10,
    verified: "মার্চ ২০২৬",
    description_bn: "AI রিসার্চ অ্যাসিস্ট্যান্ট — একাডেমিক পেপার বিশ্লেষণ করুন, ডেটা এক্সট্র্যাক্ট করুন ও রিসার্চ সারসংক্ষেপ পান।",
    review_bn: "থিসিস লিখতে হাজার পেপার পড়ার দরকার নেই — Elicit মূল তথ্য বের করে দেয়।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.4,
    direct_url: "https://elicit.com",
    affiliate_url: "",
    pricing_url: "https://elicit.com/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: false,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-27",
    bestFor: ["একাডেমিক রিসার্চ", "পেপার বিশ্লেষণ", "থিসিস", "লিটারেচার রিভিউ"],
    difficultyLevel: "মাঝারি",
    tags: ["llm", "research", "academic", "papers"],
    similarTools: ["notebooklm", "perplexity-ai", "chatgpt"],
  },

  // ── NEW TOOLS — BATCH 3 (Image/Design) ──────────────────────────────
  {
    name: "Canva AI",
    logo: "https://logo.clearbit.com/canva.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=canva.com&sz=64",
    category: "image",
    pricing: "ফ্রি / ৳১,৪৬৪",
    usdPrice: 12,
    verified: "মার্চ ২০২৬",
    description_bn: "Canva-র AI ইমেজ জেনারেটর — টেক্সট থেকে ছবি বানান, ব্যাকগ্রাউন্ড রিমুভ করুন, ডিজাইন অটো-জেনারেট করুন। বাংলাদেশে সবচেয়ে পরিচিত ডিজাইন টুল।",
    review_bn: "সোশ্যাল মিডিয়া পোস্টের জন্য Canva AI দিয়ে ১০ মিনিটে প্রফেশনাল গ্রাফিক বানাই!",
    works_in_bd: true, no_vpn: true, payment: ["card", "bkash"], rating: 4.7,
    direct_url: "https://canva.com",
    affiliate_url: "",
    pricing_url: "https://canva.com/pricing",
    supportsBangla: true,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: true,
    dateAdded: "2026-03-28",
    bestFor: ["সোশ্যাল মিডিয়া", "ডিজাইন", "থাম্বনেইল", "প্রেজেন্টেশন"],
    difficultyLevel: "সহজ",
    tags: ["image", "design", "social-media", "free"],
    similarTools: ["adobe-firefly", "ideogram", "leonardo-ai"],
  },
  {
    name: "Figma AI",
    logo: "https://logo.clearbit.com/figma.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=figma.com&sz=64",
    category: "image",
    pricing: "ফ্রি / ৳১,৮৩০",
    usdPrice: 15,
    verified: "মার্চ ২০২৬",
    description_bn: "Figma-র AI ফিচার — UI ডিজাইন অটোমেট করুন, লেআউট সাজেস্ট পান, কোড জেনারেট করুন। ফ্রিল্যান্স UI/UX ডিজাইনারদের জন্য আবশ্যক।",
    review_bn: "Figma AI দিয়ে UI মকআপ বানাতে আগের চেয়ে ৩ গুণ দ্রুত কাজ করি।",
    works_in_bd: true, no_vpn: true, payment: ["card", "wise"], rating: 4.6,
    direct_url: "https://figma.com",
    affiliate_url: "",
    pricing_url: "https://figma.com/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: false,
    paymentAccessibility: "moderate",
    featured: false,
    dateAdded: "2026-03-28",
    bestFor: ["UI ডিজাইন", "UX প্রোটোটাইপ", "ফ্রিল্যান্সিং", "ওয়েব ডিজাইন"],
    difficultyLevel: "কঠিন",
    tags: ["image", "design", "ui", "ux", "prototyping"],
    similarTools: ["canva-ai", "adobe-firefly", "looka"],
  },
  {
    name: "Adobe Express AI",
    logo: "https://logo.clearbit.com/adobe.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=adobe.com&sz=64",
    category: "image",
    pricing: "ফ্রি / ৳১,৩৪২",
    usdPrice: 11,
    verified: "মার্চ ২০২৬",
    description_bn: "Adobe-র ফ্রি AI ডিজাইন টুল — টেক্সট থেকে ছবি, ভিডিও ক্লিপ, সোশ্যাল পোস্ট। Adobe Firefly AI ইন্টিগ্রেটেড, বাংলাদেশে কার্ড দিয়ে পেমেন্ট করা যায়।",
    review_bn: "Adobe Express-এর ফ্রি প্ল্যানেই অনেক কাজ হয় — Canva-র ভালো বিকল্প।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.4,
    direct_url: "https://express.adobe.com",
    affiliate_url: "",
    pricing_url: "https://express.adobe.com/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-28",
    bestFor: ["সোশ্যাল মিডিয়া", "কুইক ডিজাইন", "ভিডিও ক্লিপ", "ব্র্যান্ডিং"],
    difficultyLevel: "সহজ",
    tags: ["image", "design", "adobe", "free", "video"],
    similarTools: ["canva-ai", "adobe-firefly", "clipdrop"],
  },
  {
    name: "Brandmark",
    logo: "https://logo.clearbit.com/brandmark.io",
    logo_fallback: "https://www.google.com/s2/favicons?domain=brandmark.io&sz=64",
    category: "image",
    pricing: "৳৩,০৫০",
    usdPrice: 25,
    verified: "মার্চ ২০২৬",
    description_bn: "AI লোগো ও ব্র্যান্ড আইডেন্টিটি ডিজাইনার — কোম্পানির নাম দিন, মিনিটে প্রফেশনাল লোগো পান। বাংলাদেশি স্টার্টআপের জন্য সাশ্রয়ী ব্র্যান্ডিং সমাধান।",
    review_bn: "স্টার্টআপের জন্য ডিজাইনার ছাড়াই প্রফেশনাল লোগো পেলাম — অবিশ্বাস্য!",
    works_in_bd: true, no_vpn: true, payment: ["card", "wise"], rating: 4.3,
    direct_url: "https://brandmark.io",
    affiliate_url: "",
    pricing_url: "https://brandmark.io/pricing",
    supportsBangla: false,
    freePlanAvailable: false,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "moderate",
    featured: false,
    dateAdded: "2026-03-28",
    bestFor: ["লোগো ডিজাইন", "ব্র্যান্ড আইডেন্টিটি", "স্টার্টআপ", "ছোট ব্যবসা"],
    difficultyLevel: "সহজ",
    tags: ["image", "logo", "branding", "design"],
    similarTools: ["looka", "canva-ai", "adobe-express-ai"],
  },

  // ── NEW TOOLS — BATCH 2 (Marketing) ──────────────────────────────────
  {
    name: "Postwise",
    logo: "https://logo.clearbit.com/postwise.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=postwise.ai&sz=64",
    category: "productivity",
    pricing: "৳৪,৫১৪",
    usdPrice: 37,
    verified: "মার্চ ২০২৬",
    description_bn: "AI টুইটার/X মার্কেটিং টুল — ভাইরাল পোস্ট লিখুন, শিডিউল করুন, অটো-এনগেজ করুন। সোশ্যাল মিডিয়া মার্কেটিং অটোমেট করতে দারুণ।",
    review_bn: "Postwise দিয়ে X-এ ফলোয়ার বাড়ানো অনেক সহজ হয়ে গেছে — মার্কেটিং টাইম বাঁচে।",
    works_in_bd: true, no_vpn: true, payment: ["card", "wise"], rating: 4.2,
    direct_url: "https://postwise.ai",
    affiliate_url: "",
    pricing_url: "https://postwise.ai/pricing",
    supportsBangla: false,
    freePlanAvailable: false,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "moderate",
    featured: false,
    dateAdded: "2026-03-28",
    bestFor: ["সোশ্যাল মিডিয়া মার্কেটিং", "Twitter/X", "কন্টেন্ট শিডিউলিং", "এনগেজমেন্ট"],
    difficultyLevel: "সহজ",
    tags: ["productivity", "marketing", "social-media", "twitter"],
    similarTools: ["buffer-ai", "jasper-ai", "copy-ai"],
  },
  {
    name: "Taplio",
    logo: "https://logo.clearbit.com/taplio.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=taplio.com&sz=64",
    category: "productivity",
    pricing: "৳৪,৭৫৮",
    usdPrice: 39,
    verified: "মার্চ ২০২৬",
    description_bn: "LinkedIn মার্কেটিং AI — প্রফেশনাল পোস্ট লিখুন, নেটওয়ার্ক বাড়ান, লিড জেনারেট করুন। বাংলাদেশি প্রফেশনাল ও ফ্রিল্যান্সারদের জন্য দারুণ।",
    review_bn: "Taplio দিয়ে LinkedIn-এ ক্লায়েন্ট পাওয়া সহজ হয়েছে — প্রতি সপ্তাহে ৩-৪টি লিড আসে।",
    works_in_bd: true, no_vpn: true, payment: ["card", "wise"], rating: 4.3,
    direct_url: "https://taplio.com",
    affiliate_url: "",
    pricing_url: "https://taplio.com/pricing",
    supportsBangla: false,
    freePlanAvailable: false,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "moderate",
    featured: false,
    dateAdded: "2026-03-28",
    bestFor: ["LinkedIn মার্কেটিং", "নেটওয়ার্কিং", "লিড জেনারেশন", "ফ্রিল্যান্সিং"],
    difficultyLevel: "সহজ",
    tags: ["productivity", "marketing", "linkedin", "networking"],
    similarTools: ["postwise", "buffer-ai", "jasper-ai"],
  },
  {
    name: "Mailmodo",
    logo: "https://logo.clearbit.com/mailmodo.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=mailmodo.com&sz=64",
    category: "productivity",
    pricing: "ফ্রি / ৳৪,৭৫৮",
    usdPrice: 39,
    verified: "মার্চ ২০২৬",
    description_bn: "AI ইমেইল মার্কেটিং প্ল্যাটফর্ম — ইন্টারেক্টিভ ইমেইল ক্যাম্পেইন তৈরি করুন, অটোমেশন সেট করুন, কনভার্শন বাড়ান। ই-কমার্স ব্যবসার জন্য আদর্শ।",
    review_bn: "Mailmodo-র AMP ইমেইল দিয়ে আমাদের ক্যাম্পেইনের ক্লিক রেট ৩ গুণ বেড়েছে।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.3,
    direct_url: "https://mailmodo.com",
    affiliate_url: "",
    pricing_url: "https://mailmodo.com/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: false,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-28",
    bestFor: ["ইমেইল মার্কেটিং", "ক্যাম্পেইন অটোমেশন", "ই-কমার্স", "লিড নার্চারিং"],
    difficultyLevel: "মাঝারি",
    tags: ["productivity", "marketing", "email", "automation"],
    similarTools: ["jasper-ai", "copy-ai", "writesonic"],
  },

  // ── NEW TOOLS — BATCH 4 (Coding) ─────────────────────────────────────
  {
    name: "Devin AI",
    logo: "https://logo.clearbit.com/cognition.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=cognition.ai&sz=64",
    category: "coding",
    pricing: "৳৬১,০০০",
    usdPrice: 500,
    verified: "মার্চ ২০২৬",
    description_bn: "বিশ্বের প্রথম AI সফটওয়্যার ইঞ্জিনিয়ার — পুরো প্রজেক্ট একা কোড করতে পারে, বাগ ঠিক করে, ডিপ্লয় করে। Enterprise-level AI coding agent।",
    review_bn: "Devin দিয়ে ৩ দিনের কাজ ৩ ঘণ্টায় শেষ করলাম — ভবিষ্যতের কোডিং এটাই।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.1,
    direct_url: "https://cognition.ai",
    affiliate_url: "",
    pricing_url: "https://cognition.ai/pricing",
    supportsBangla: false,
    freePlanAvailable: false,
    mobileFriendly: false,
    beginnerFriendly: false,
    paymentAccessibility: "moderate",
    featured: false,
    dateAdded: "2026-03-28",
    bestFor: ["ফুল প্রজেক্ট ডেভেলপমেন্ট", "বাগ ফিক্সিং", "কোড রিভিউ", "এন্টারপ্রাইজ"],
    difficultyLevel: "কঠিন",
    tags: ["coding", "agent", "autonomous", "enterprise"],
    similarTools: ["cursor", "bolt-new", "lovable"],
  },
  {
    name: "Aider",
    logo: "https://logo.clearbit.com/aider.chat",
    logo_fallback: "https://www.google.com/s2/favicons?domain=aider.chat&sz=64",
    category: "coding",
    pricing: "ফ্রি (ওপেন সোর্স)",
    usdPrice: 0,
    verified: "মার্চ ২০২৬",
    description_bn: "ওপেন সোর্স AI কোডিং অ্যাসিস্ট্যান্ট — টার্মিনালে চালান, গিটহাব কোডবেস বুঝে কোড লেখে। ডেভেলপারদের জন্য বিনামূল্যে শক্তিশালী টুল।",
    review_bn: "Aider দিয়ে পুরোনো কোডবেসে নতুন ফিচার যোগ করা এখন অনেক সহজ।",
    works_in_bd: true, no_vpn: true, payment: [], rating: 4.4,
    direct_url: "https://aider.chat",
    affiliate_url: "",
    pricing_url: "https://aider.chat",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: false,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-28",
    bestFor: ["কোডবেস রিফ্যাক্টর", "ওপেন সোর্স প্রজেক্ট", "টার্মিনাল কোডিং", "বিনামূল্যে"],
    difficultyLevel: "কঠিন",
    tags: ["coding", "open-source", "free", "terminal"],
    similarTools: ["cursor", "github-copilot", "codeium"],
  },
  {
    name: "Continue.dev",
    logo: "https://logo.clearbit.com/continue.dev",
    logo_fallback: "https://www.google.com/s2/favicons?domain=continue.dev&sz=64",
    category: "coding",
    pricing: "ফ্রি (ওপেন সোর্স)",
    usdPrice: 0,
    verified: "মার্চ ২০২৬",
    description_bn: "VS Code ও JetBrains-এর জন্য ফ্রি AI কোডিং এক্সটেনশন — যেকোনো LLM কানেক্ট করুন, অটোকমপ্লিট ও চ্যাট পান। GitHub Copilot-এর বিনামূল্যে বিকল্প।",
    review_bn: "Continue.dev ফ্রিতে Copilot-এর মতো কাজ করে — বাংলাদেশি ডেভেলপারদের জন্য আদর্শ।",
    works_in_bd: true, no_vpn: true, payment: [], rating: 4.5,
    direct_url: "https://continue.dev",
    affiliate_url: "",
    pricing_url: "https://continue.dev",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: false,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-28",
    bestFor: ["VS Code", "JetBrains", "ফ্রি কোডিং AI", "অটোকমপ্লিট"],
    difficultyLevel: "মাঝারি",
    tags: ["coding", "open-source", "free", "vscode", "extension"],
    similarTools: ["github-copilot", "codeium", "tabnine"],
  },

  // ── NEW TOOLS — BATCH 5 (LLM & Productivity) ─────────────────────────
  {
    name: "Consensus",
    logo: "https://logo.clearbit.com/consensus.app",
    logo_fallback: "https://www.google.com/s2/favicons?domain=consensus.app&sz=64",
    category: "llm",
    pricing: "ফ্রি / ৳১,২১৮",
    usdPrice: 9.99,
    verified: "মার্চ ২০২৬",
    description_bn: "AI সায়েন্টিফিক সার্চ ইঞ্জিন — ১০ কোটিরও বেশি রিসার্চ পেপার থেকে প্রমাণ-ভিত্তিক উত্তর খুঁজুন। মেডিকেল, সায়েন্স ও একাডেমিক রিসার্চের জন্য।",
    review_bn: "মেডিকেল স্টুডেন্ট হিসেবে Consensus আমার রিসার্চ অনেক সহজ করে দিয়েছে।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.5,
    direct_url: "https://consensus.app",
    affiliate_url: "",
    pricing_url: "https://consensus.app/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-28",
    bestFor: ["মেডিকেল রিসার্চ", "সায়েন্টিফিক পেপার", "একাডেমিক", "এভিডেন্স-বেসড"],
    difficultyLevel: "সহজ",
    tags: ["llm", "research", "science", "academic"],
    similarTools: ["elicit", "perplexity-ai", "notebooklm"],
  },
  {
    name: "Kagi",
    logo: "https://logo.clearbit.com/kagi.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=kagi.com&sz=64",
    category: "llm",
    pricing: "৳১,২২০",
    usdPrice: 10,
    verified: "মার্চ ২০২৬",
    description_bn: "বিজ্ঞাপন-মুক্ত প্রিমিয়াম সার্চ ইঞ্জিন + AI অ্যাসিস্ট্যান্ট — গোপনীয়তা রক্ষা করে, সঠিক রেজাল্ট দেয়। Google-এর বিকল্প খুঁজছেন?",
    review_bn: "Kagi-তে কোনো বিজ্ঞাপন নেই — সার্চ রেজাল্ট অনেক ভালো ও ফাস্ট।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.4,
    direct_url: "https://kagi.com",
    affiliate_url: "",
    pricing_url: "https://kagi.com/pricing",
    supportsBangla: false,
    freePlanAvailable: false,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "moderate",
    featured: false,
    dateAdded: "2026-03-28",
    bestFor: ["প্রাইভেট সার্চ", "বিজ্ঞাপন-মুক্ত", "গবেষণা", "প্রিমিয়াম সার্চ"],
    difficultyLevel: "সহজ",
    tags: ["llm", "search", "privacy", "ad-free"],
    similarTools: ["perplexity-ai", "you-com", "chatgpt"],
  },
  {
    name: "Tome",
    logo: "https://logo.clearbit.com/tome.app",
    logo_fallback: "https://www.google.com/s2/favicons?domain=tome.app&sz=64",
    category: "productivity",
    pricing: "ফ্রি / ৳১,৯৫২",
    usdPrice: 16,
    verified: "মার্চ ২০২৬",
    description_bn: "AI প্রেজেন্টেশন ও স্টোরিটেলিং টুল — আইডিয়া দিন, মিনিটে পুরো স্লাইড ডেক তৈরি হয়ে যাবে। বিজনেস পিচ ও রিপোর্টের জন্য দারুণ।",
    review_bn: "বিনিয়োগকারীদের জন্য পিচ ডেক Tome দিয়ে ৩০ মিনিটে বানিয়ে ফেললাম!",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.3,
    direct_url: "https://tome.app",
    affiliate_url: "",
    pricing_url: "https://tome.app/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-28",
    bestFor: ["প্রেজেন্টেশন", "পিচ ডেক", "স্টোরিটেলিং", "বিজনেস রিপোর্ট"],
    difficultyLevel: "সহজ",
    tags: ["productivity", "presentation", "slides", "business"],
    similarTools: ["gamma", "beautiful-ai", "canva-ai"],
  },
  {
    name: "Mem AI",
    logo: "https://logo.clearbit.com/mem.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=mem.ai&sz=64",
    category: "productivity",
    pricing: "ফ্রি / ৳১,৮২৮",
    usdPrice: 14.99,
    verified: "মার্চ ২০২৬",
    description_bn: "AI নোট-টেকিং ও নলেজ ম্যানেজমেন্ট — নোট নিন, AI দিয়ে কানেক্ট করুন, যেকোনো তথ্য খুঁজে পান। Notion-এর AI-ফার্স্ট বিকল্প।",
    review_bn: "Mem AI দিয়ে সব নোট অর্গানাইজ থাকে — কিছু খুঁজতে আর ঘণ্টার পর ঘণ্টা নষ্ট হয় না।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.2,
    direct_url: "https://mem.ai",
    affiliate_url: "",
    pricing_url: "https://mem.ai/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-28",
    bestFor: ["নোট-টেকিং", "নলেজ ম্যানেজমেন্ট", "রিসার্চ", "টিম কোলাবোরেশন"],
    difficultyLevel: "সহজ",
    tags: ["productivity", "notes", "knowledge", "organization"],
    similarTools: ["notion-ai", "notebooklm", "taskade-ai"],
  },
  {
    name: "Craft AI",
    logo: "https://logo.clearbit.com/craft.do",
    logo_fallback: "https://www.google.com/s2/favicons?domain=craft.do&sz=64",
    category: "productivity",
    pricing: "ফ্রি / ৳৬১০",
    usdPrice: 5,
    verified: "মার্চ ২০২৬",
    description_bn: "AI ডকুমেন্ট ও নোটস অ্যাপ — সুন্দর ডকুমেন্ট লিখুন, AI দিয়ে সম্পাদনা করুন, টিমের সাথে শেয়ার করুন। Apple ডিজাইন অ্যাওয়ার্ড বিজয়ী।",
    review_bn: "Craft-এর ডিজাইন অসাধারণ — ডকুমেন্ট লেখা এখন আনন্দদায়ক কাজ।",
    works_in_bd: true, no_vpn: true, payment: ["card"], rating: 4.5,
    direct_url: "https://craft.do",
    affiliate_url: "",
    pricing_url: "https://craft.do/pricing",
    supportsBangla: false,
    freePlanAvailable: true,
    mobileFriendly: true,
    beginnerFriendly: true,
    paymentAccessibility: "easy",
    featured: false,
    dateAdded: "2026-03-28",
    bestFor: ["ডকুমেন্ট রাইটিং", "নোটস", "টিম কোলাবোরেশন", "Apple ডিভাইস"],
    difficultyLevel: "সহজ",
    tags: ["productivity", "notes", "documents", "writing"],
    similarTools: ["notion-ai", "mem-ai", "taskade-ai"],
  },
];
