// BanglaAIGuide — tools-data.js
// Logos via Clearbit API: https://logo.clearbit.com/{domain}
// No API key needed. Free to use.
// Fallback: Google Favicon API if Clearbit fails

const USD_TO_BDT = 122;

const tools = [

  // ── LLMs & CHATBOTS ──────────────────────────────────────────────
  {
    name: "ChatGPT",
    logo: "https://logo.clearbit.com/chatgpt.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=chatgpt.com&sz=64",
    category: "llm",
    pricing: "freemium",
    usdPrice: "Free / $8/mo (Go) / $20/mo (Plus) / $200/mo (Pro)",
    verified: "মার্চ ২০২৬",
    details: "Free tier available with limited usage (10 messages/5 hours). New Go plan launched 2026. Business plan $25-30/user/mo. Pricing adjustments in 2026.",
    description_bn: "OpenAI-এর সবচেয়ে জনপ্রিয় AI চ্যাটবট। লেখা, বিশ্লেষণ, কোড — সব কাজে দারুণ।",
    review_bn: "ফ্রিলান্সিংয়ের জন্য এটা দিয়ে ক্লায়েন্ট ইমেইল লিখি, অনেক সময় বাঁচে!",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.8,
    direct_url: "https://chatgpt.com",
    affiliate_url: "https://chatgpt.com",
    pricing_url: "https://openai.com/chatgpt/pricing",
  },
  {
    name: "Claude",
    logo: "https://logo.clearbit.com/anthropic.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=anthropic.com&sz=64",
    category: "llm",
    pricing: "freemium",
    usdPrice: "Free / $20/mo (Pro) / $100-200/mo (Max)",
    verified: "মার্চ ২০২৬",
    details: "Free tier with limited usage. Max 5x at $100/mo, Max 20x at $200/mo. Team plan $25/user/mo. No recent pricing changes.",
    description_bn: "Anthropic-এর AI — বাংলায় কথা বলে, লম্বা ডকুমেন্ট বিশ্লেষণ করে, কোড লেখে।",
    review_bn: "বাংলা কন্টেন্ট তৈরিতে Claude আমার ফার্স্ট চয়েস। বাংলা বোঝে ভালো!",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.9,
    direct_url: "https://claude.ai",
    affiliate_url: "https://claude.ai",
    pricing_url: "https://claude.ai/pricing",
  },
  {
    name: "Gemini",
    logo: "https://logo.clearbit.com/google.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=gemini.google.com&sz=64",
    category: "llm",
    pricing: "freemium",
    usdPrice: "Free / $19.99/mo (AI Pro) / ~$42/mo (AI Ultra)",
    verified: "মার্চ ২০২৬",
    details: "Free tier available. AI Ultra is $124.99 for 3 months. Includes Google Workspace integration. No major pricing changes.",
    description_bn: "Google-এর AI মডেল। ইন্টারনেট সার্চ যুক্ত, বাংলা ভাষায় ভালো সাপোর্ট।",
    review_bn: "Google Docs-এর সাথে ইন্টিগ্রেশন অসাধারণ। কাজ অনেক দ্রুত হয়।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.6,
    direct_url: "https://gemini.google.com",
    affiliate_url: "https://gemini.google.com",
    pricing_url: "https://one.google.com/about/plans",
  },
  {
    name: "Perplexity AI",
    logo: "https://logo.clearbit.com/perplexity.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=perplexity.ai&sz=64",
    category: "llm",
    pricing: "freemium",
    usdPrice: "Free / $20/mo (Pro) / $200/mo (Max)",
    verified: "মার্চ ২০২৬",
    details: "Free plan with 5 Pro searches/day. Enterprise Pro $40/seat/mo, Enterprise Max $325/seat/mo. Stable pricing.",
    description_bn: "AI দিয়ে ওয়েব সার্চ — সোর্স সহ উত্তর দেয়। রিসার্চ কাজে সেরা।",
    review_bn: "রিসার্চের জন্য এটাই ব্যবহার করি। কোথা থেকে তথ্য নিয়েছে সেটাও দেখায়।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.7,
    direct_url: "https://www.perplexity.ai",
    affiliate_url: "https://www.perplexity.ai",
    pricing_url: "https://www.perplexity.ai/pro",
  },
  {
    name: "Groq",
    logo: "https://logo.clearbit.com/groq.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=groq.com&sz=64",
    category: "llm",
    pricing: "freemium",
    usdPrice: "Free / Pay-as-you-go (API)",
    verified: "মার্চ ২০২৬",
    details: "Free tier available. Developer plan is pay-as-you-go ($0.06-0.99 per million tokens). 50% discount for batch API. Very low pricing.",
    description_bn: "বিদ্যুৎ গতির LLM inference। Llama ও Mixtral মডেল চালায়।",
    review_bn: "API কলে সবচেয়ে দ্রুত রেসপন্স পাই। বাংলাদেশ থেকে কোনো সমস্যা নেই।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.4,
    direct_url: "https://groq.com",
    affiliate_url: "https://groq.com",
    pricing_url: "https://groq.com",
  },
  {
    name: "Mistral AI",
    logo: "https://logo.clearbit.com/mistral.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=mistral.ai&sz=64",
    category: "llm",
    pricing: "freemium",
    usdPrice: "Free / $14.99/mo (Le Chat Pro) / Pay-as-you-go (API)",
    verified: "মার্চ ২০২৬",
    details: "Free tier for Le Chat. Pro plan $14.99/mo. API pricing varies by model ($0.02-2.00 per million input tokens).",
    description_bn: "ইউরোপের সেরা ওপেনসোর্স LLM। ডেটা প্রাইভেসি ভালো, cost-effective।",
    review_bn: "ChatGPT-এর ভালো বিকল্প। ফ্রিতে অনেক কাজ হয়।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.3,
    direct_url: "https://mistral.ai",
    affiliate_url: "https://mistral.ai",
    pricing_url: "https://mistral.ai",
  },
  {
    name: "Poe",
    logo: "https://logo.clearbit.com/poe.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=poe.com&sz=64",
    category: "llm",
    pricing: "freemium",
    usdPrice: "Free / $17/mo (Premium)",
    verified: "মার্চ ২০২৬",
    details: "Free plan with limited daily credits. Premium plans start at $4.99/mo, full access ~$17/mo. Multi-model access platform.",
    description_bn: "এক জায়গায় GPT-4, Claude, Gemini সব। নিজের বট তৈরি করা যায়।",
    review_bn: "একটা অ্যাপ দিয়ে সব AI ব্যবহার করা যায় — এটাই সবচেয়ে সুবিধা।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.3,
    direct_url: "https://poe.com",
    affiliate_url: "https://poe.com",
    pricing_url: "https://poe.com",
  },
  {
    name: "Meta AI",
    logo: "https://logo.clearbit.com/meta.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=meta.ai&sz=64",
    category: "llm",
    pricing: "free",
    usdPrice: "Free",
    verified: "মার্চ ২০২৬",
    details: "Completely free. Integrated into Facebook, Instagram, WhatsApp. No paid tiers.",
    description_bn: "Meta-র Llama AI — WhatsApp ও Instagram-এ বিল্টইন। বাংলায়ও কথা বলে।",
    review_bn: "WhatsApp-এ সরাসরি ব্যবহার করা যায়। বাংলায় উত্তর দেয়!",
    works_in_bd: true, no_vpn: true, payment: "free", rating: 4.1,
    direct_url: "https://www.meta.ai",
    affiliate_url: "https://www.meta.ai",
    pricing_url: "https://www.meta.ai",
  },
  {
    name: "HuggingChat",
    logo: "https://logo.clearbit.com/huggingface.co",
    logo_fallback: "https://www.google.com/s2/favicons?domain=huggingface.co&sz=64",
    category: "llm",
    pricing: "free",
    usdPrice: "সম্পূর্ণ ফ্রি",
    verified: "মার্চ ২০২৬",
    description_bn: "Hugging Face-এর ফ্রি chatbot। ওপেনসোর্স মডেল, ডেটা কোথাও বিক্রি হয় না।",
    review_bn: "যাদের বাজেট কম তাদের জন্য দারুণ অপশন। সম্পূর্ণ ফ্রি!",
    works_in_bd: true, no_vpn: true, payment: "free", rating: 4.0,
    direct_url: "https://huggingface.co/chat",
    affiliate_url: "https://huggingface.co/chat",
    pricing_url: "https://huggingface.co/chat",
  },
  {
    name: "DeepSeek",
    logo: "https://logo.clearbit.com/deepseek.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=deepseek.com&sz=64",
    category: "llm",
    pricing: "free",
    usdPrice: "সম্পূর্ণ ফ্রি",
    verified: "মার্চ ২০২৬",
    description_bn: "চীনের DeepSeek — কোডিং ও ম্যাথে ChatGPT-4 এর চেয়ে ভালো। রিজনিং মডেল সম্পূর্ণ ফ্রি।",
    review_bn: "কোডিং সমস্যা সমাধানে এটি এখন আমার প্রথম পছন্দ। ফ্রি অথচ শক্তিশালী!",
    works_in_bd: true, no_vpn: true, payment: "free", rating: 4.7,
    direct_url: "https://chat.deepseek.com",
    affiliate_url: "https://chat.deepseek.com",
    pricing_url: "https://chat.deepseek.com",
  },
  {
    name: "Grok",
    logo: "https://logo.clearbit.com/x.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=grok.com&sz=64",
    category: "llm",
    pricing: "freemium",
    usdPrice: "Free (limited) / $8/mo (X Premium) / $16/mo (X Premium+)",
    verified: "মার্চ ২০২৬",
    details: "Free tier on X with limitations. X Premium $8/mo, Premium+ $16/mo includes full Grok access and Aurora image gen.",
    description_bn: "Elon Musk-এর xAI। X (Twitter) রিয়েল-টাইম ডেটা অ্যাক্সেস করে।",
    review_bn: "X প্ল্যাটফর্মের ট্রেন্ড ট্র্যাক করতে কাজে আসে।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.2,
    direct_url: "https://grok.com",
    affiliate_url: "https://grok.com",
    pricing_url: "https://grok.com",
  },

  // ── IMAGE & VIDEO ─────────────────────────────────────────────────
  {
    name: "Midjourney",
    logo: "https://logo.clearbit.com/midjourney.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=midjourney.com&sz=64",
    category: "image",
    pricing: "paid",
    usdPrice: "$10/mo (Basic) / $30/mo (Standard) / $60/mo (Pro) / $120/mo (Mega)",
    verified: "মার্চ ২০২৬",
    details: "No free tier. Annual billing saves 20%. Stealth Mode (privacy) requires Pro plan minimum. No recent pricing changes.",
    description_bn: "বিশ্বের সেরা AI আর্ট জেনারেটর। Discord-এর মাধ্যমে ব্যবহার।",
    review_bn: "ফ্রিল্যান্স গ্রাফিক কাজে এটা দিয়ে অনেক ক্লায়েন্ট পেয়েছি!",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.9,
    direct_url: "https://www.midjourney.com",
    affiliate_url: "https://www.midjourney.com",
    pricing_url: "https://www.midjourney.com/account",
  },
  {
    name: "Ideogram",
    logo: "https://logo.clearbit.com/ideogram.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=ideogram.ai&sz=64",
    category: "image",
    pricing: "freemium",
    usdPrice: "Free / $16/mo (Plus)",
    verified: "মার্চ ২০২৬",
    details: "Free tier available and genuinely usable. Plus plan $16/mo for private generation. Excellent text rendering.",
    description_bn: "ছবিতে টেক্সট লেখার জন্য সেরা AI। থাম্বনেইল ও পোস্টার তৈরিতে অপ্রতিদ্বন্দ্বী।",
    review_bn: "YouTube থাম্বনেইলের জন্য এটা use করি। বাংলা টেক্সটও সুন্দর আসে!",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.6,
    direct_url: "https://ideogram.ai",
    affiliate_url: "https://ideogram.ai",
    pricing_url: "https://ideogram.ai/pricing",
  },
  {
    name: "Kling AI",
    logo: "https://logo.clearbit.com/klingai.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=klingai.com&sz=64",
    category: "image",
    pricing: "freemium",
    usdPrice: "~$10/mo (via Artlist)",
    verified: "মার্চ ২০২৬",
    details: "Accessible through Artlist platform. Strong image-to-video generation. Pricing competitive with market.",
    description_bn: "হাই-কোয়ালিটি AI ভিডিও জেনারেটর। টেক্সট-টু-ভিডিও ও ইমেজ অ্যানিমেশন।",
    review_bn: "বাংলা অ্যানিমেশন কন্টেন্টের জন্য এটা ব্যবহার করছি। রেজাল্ট দারুণ!",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.5,
    direct_url: "https://klingai.com",
    affiliate_url: "https://klingai.com",
    pricing_url: "https://klingai.com/pricing",
  },
  {
    name: "Runway ML",
    logo: "https://logo.clearbit.com/runwayml.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=runwayml.com&sz=64",
    category: "image",
    pricing: "freemium",
    usdPrice: "Free (125 credits) / $12/mo (Standard)",
    verified: "মার্চ ২০২৬",
    details: "Free tier with 125 one-time credits. Standard plan $12/mo (annual billing). Gen-4 model available.",
    description_bn: "প্রফেশনাল AI ভিডিও এডিটিং ও জেনারেশন। Gen-2 মডেল দিয়ে অবাক করা ভিডিও।",
    review_bn: "ইউটিউব কন্টেন্টে B-roll তৈরিতে দারুণ। সময় ও টাকা দুটোই বাঁচে।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.6,
    direct_url: "https://runwayml.com",
    affiliate_url: "https://runwayml.com",
    pricing_url: "https://runwayml.com/pricing",
  },
  {
    name: "Leonardo AI",
    logo: "https://logo.clearbit.com/leonardo.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=leonardo.ai&sz=64",
    category: "image",
    pricing: "freemium",
    usdPrice: "Free (150 tokens/day) / $10/mo (Apprentice) / $24/mo (Artisan) / $48/mo (Maestro)",
    verified: "মার্চ ২০২৬",
    details: "Free tier with 150 daily tokens. Token-based pricing system. Commercial rights on paid plans.",
    description_bn: "গেম অ্যাসেট, ইলাস্ট্রেশন ও কনসেপ্ট আর্টের জন্য ফাইন-টিউন মডেল।",
    review_bn: "ফ্রি টায়ারে প্রতিদিন ১৫০ ক্রেডিট পাওয়া যায়। কোনো সমস্যা নেই!",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.5,
    direct_url: "https://leonardo.ai",
    affiliate_url: "https://leonardo.ai",
    pricing_url: "https://leonardo.ai/pricing",
  },
  {
    name: "Stable Diffusion",
    logo: "https://logo.clearbit.com/stability.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=stability.ai&sz=64",
    category: "image",
    pricing: "free",
    usdPrice: "সম্পূর্ণ ফ্রি",
    verified: "মার্চ ২০২৬",
    description_bn: "ওপেনসোর্স ইমেজ মডেল — নিজের PC-তে চালানো যায়। সর্বোচ্চ কাস্টমাইজেশন।",
    review_bn: "লোকালি চালাই, তাই কোনো API খরচ নেই।",
    works_in_bd: true, no_vpn: true, payment: "free", rating: 4.5,
    direct_url: "https://stability.ai",
    affiliate_url: "https://stability.ai",
    pricing_url: "https://stability.ai",
  },
  {
    name: "Adobe Firefly",
    logo: "https://logo.clearbit.com/adobe.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=firefly.adobe.com&sz=64",
    category: "image",
    pricing: "freemium",
    usdPrice: "Free / $9.99/mo (Standard) / $19.99/mo (Pro) / $199.99/mo (Premium)",
    verified: "মার্চ ২০২৬",
    details: "Free tier available. Credit-based system. Unlimited standard generations on paid plans. Integrated with Creative Cloud.",
    description_bn: "Adobe-র কমার্শিয়ালি সেফ AI। Photoshop ও Illustrator-এর সাথে ইন্টিগ্রেটেড।",
    review_bn: "ফ্রিলান্স ডিজাইন কাজে কমার্শিয়াল লাইসেন্সের চিন্তা নেই।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.3,
    direct_url: "https://firefly.adobe.com",
    affiliate_url: "https://firefly.adobe.com",
    pricing_url: "https://firefly.adobe.com",
  },
  {
    name: "Flux",
    logo: "https://logo.clearbit.com/blackforestlabs.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=blackforestlabs.ai&sz=64",
    category: "image",
    pricing: "freemium",
    usdPrice: "Free / API paid",
    verified: "মার্চ ২০২৬",
    description_bn: "Black Forest Labs-এর স্টেট-অফ-দ্যা-আর্ট ইমেজ মডেল। অত্যন্ত রিয়েলিস্টিক।",
    review_bn: "Midjourney-র বিকল্প হিসেবে ব্যবহার শুরু করেছি। কোয়ালিটি অসাধারণ!",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.6,
    direct_url: "https://blackforestlabs.ai",
    affiliate_url: "https://blackforestlabs.ai",
    pricing_url: "https://blackforestlabs.ai",
  },

  // ── CODING ────────────────────────────────────────────────────────
  {
    name: "Cursor",
    logo: "https://logo.clearbit.com/cursor.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=cursor.com&sz=64",
    category: "coding",
    pricing: "freemium",
    usdPrice: "Free / $20/mo (Pro)",
    verified: "মার্চ ২০২৬",
    details: "Free tier available. Pro plan $20/mo for advanced AI features. AI-native code editor fork of VS Code.",
    description_bn: "AI-ফার্স্ট কোড এডিটর। স্বাভাবিক ভাষায় কোড লিখুন, এডিট করুন, ডিবাগ করুন।",
    review_bn: "এই একটা টুল দিয়ে আমার কোডিং স্পিড ৩ গুণ বেড়েছে!",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.9,
    direct_url: "https://cursor.com",
    affiliate_url: "https://cursor.com/affiliates",
    pricing_url: "https://cursor.com/pricing",
  },
  {
    name: "GitHub Copilot",
    logo: "https://logo.clearbit.com/github.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=github.com&sz=64",
    category: "coding",
    pricing: "freemium",
    usdPrice: "Free (limited) / $10/mo (Individual) / $19/user/mo (Business)",
    verified: "মার্চ ২০২৬",
    details: "Free tier with 2,000 completions. Students/open-source free. Half the price of Cursor at every tier.",
    description_bn: "IDE-র ভেতরেই AI পেয়ার প্রোগ্রামার। অটোকমপ্লিট, চ্যাট ও কোড রিভিউ।",
    review_bn: "VS Code-এ কাজ করি, Copilot থেকে আর বের হতে পারি না!",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.7,
    direct_url: "https://github.com/features/copilot",
    affiliate_url: "https://github.com/features/copilot",
    pricing_url: "https://github.com/features/copilot#pricing",
  },
  {
    name: "Bolt.new",
    logo: "https://logo.clearbit.com/bolt.new",
    logo_fallback: "https://www.google.com/s2/favicons?domain=bolt.new&sz=64",
    category: "coding",
    pricing: "freemium",
    usdPrice: "Free tier / Paid plans available",
    verified: "মার্চ ২০২৬",
    details: "Free tier available for testing. Paid plans for production use. StackBlitz-powered vibe coding platform.",
    description_bn: "ব্রাউজারেই ফুল-স্ট্যাক অ্যাপ বানান। কোনো সেটআপ ছাড়াই প্রম্পট দিয়ে অ্যাপ।",
    review_bn: "ক্লায়েন্টকে ডেমো দেওয়ার জন্য ১ ঘন্টায় পুরো অ্যাপ বানাই!",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.5,
    direct_url: "https://bolt.new",
    affiliate_url: "https://bolt.new",
    pricing_url: "https://bolt.new/pricing",
  },
  {
    name: "v0 by Vercel",
    logo: "https://logo.clearbit.com/vercel.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=v0.dev&sz=64",
    category: "coding",
    pricing: "freemium",
    usdPrice: "Free ($5 credits) / $20/mo",
    verified: "মার্চ ২০২৬",
    details: "Free tier with $5 compute credits. Paid plan $20/mo for individuals. React/Next.js focused UI generator.",
    description_bn: "প্রম্পট থেকে React + Tailwind UI কম্পোনেন্ট। Vercel-এ ইনস্ট্যান্ট ডিপ্লয়।",
    review_bn: "UI ডিজাইনের জন্য ফ্রন্টএন্ড ডেভেলপার লাগে না আর।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.5,
    direct_url: "https://v0.dev",
    affiliate_url: "https://v0.dev",
    pricing_url: "https://v0.dev",
  },
  {
    name: "Windsurf",
    logo: "https://logo.clearbit.com/windsurf.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=windsurf.com&sz=64",
    category: "coding",
    pricing: "freemium",
    usdPrice: "Free (individuals) / $15/mo",
    verified: "মার্চ ২০২৬",
    details: "Free tier for individual developers. $15/mo for paid plan. Competitive with Cursor and Copilot.",
    description_bn: "Codeium-এর AI কোড এডিটর। 'Flow' ফিচার দিয়ে পুরো প্রজেক্ট এজেন্টিকভাবে বানায়।",
    review_bn: "Cursor-এর ভালো ফ্রি বিকল্প। বাংলাদেশ থেকে কোনো সমস্যা নেই।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.5,
    direct_url: "https://windsurf.com",
    affiliate_url: "https://windsurf.com",
    pricing_url: "https://windsurf.com",
  },
  {
    name: "Replit AI",
    logo: "https://logo.clearbit.com/replit.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=replit.com&sz=64",
    category: "coding",
    pricing: "freemium",
    usdPrice: "Free (Starter) / $20-25/mo (Core) / $100/mo (Pro)",
    verified: "মার্চ ২০২৬",
    details: "Free Starter plan. Core $20/mo (annual) or $25/mo (monthly). New Pro plan $100/mo for teams up to 15 users. Usage-based credits.",
    description_bn: "ব্রাউজার-বেসড IDE + AI। ইনস্ট্যান্ট ডেভেলপমেন্ট এনভায়রনমেন্ট।",
    review_bn: "কম্পিউটারে সেটআপ ছাড়াই কোড লেখা ও রান করা যায়।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.2,
    direct_url: "https://replit.com",
    affiliate_url: "https://replit.com",
    pricing_url: "https://replit.com/pricing",
  },
  {
    name: "Claude Code",
    logo: "https://logo.clearbit.com/anthropic.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=anthropic.com&sz=64",
    category: "coding",
    pricing: "paid",
    usdPrice: "Usage-based",
    verified: "মার্চ ২০২৬",
    description_bn: "Anthropic-এর টার্মিনাল AI। পুরো প্রজেক্ট প্ল্যান করে, কোড লেখে, ডিবাগ করে।",
    review_bn: "SaaS প্রজেক্টের জন্য এটা ব্যবহার করছি। সত্যিকারের এজেন্টিক কোডিং।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.7,
    direct_url: "https://claude.ai/code",
    affiliate_url: "https://claude.ai/code",
    pricing_url: "https://claude.ai/code",
  },

  // ── PRODUCTIVITY ──────────────────────────────────────────────────
  {
    name: "ElevenLabs",
    logo: "https://logo.clearbit.com/elevenlabs.io",
    logo_fallback: "https://www.google.com/s2/favicons?domain=elevenlabs.io&sz=64",
    category: "productivity",
    pricing: "freemium",
    usdPrice: "Free (10k credits) / $1/mo (Starter promo) / $11-22/mo (Creator)",
    verified: "মার্চ ২০২৬",
    details: "Free tier with 10k credits. Promotional pricing available (50-80% off). Creator plan normally $22/mo. Professional voice cloning on paid plans.",
    description_bn: "সেরা AI ভয়েস সিন্থেসিস। ভয়েস ক্লোনিং, টেক্সট-টু-স্পিচ ২৯টি ভাষায়।",
    review_bn: "বাংলা পডকাস্ট ও ভয়েসওভারের জন্য দারুণ। বাংলা উচ্চারণও বেশ ভালো!",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.8,
    direct_url: "https://elevenlabs.io",
    affiliate_url: "https://elevenlabs.io/affiliates",
    pricing_url: "https://elevenlabs.io/pricing",
  },
  {
    name: "Gamma",
    logo: "https://logo.clearbit.com/gamma.app",
    logo_fallback: "https://www.google.com/s2/favicons?domain=gamma.app&sz=64",
    category: "productivity",
    pricing: "freemium",
    usdPrice: "Free (400 credits) / $8/mo (Plus) / $15-20/mo (Pro) / $100/mo (Ultra)",
    verified: "মার্চ ২০২৬",
    details: "Free plan with 400 AI credits. Plus $8/mo (annual) or $10/mo (monthly). AI presentation maker. No recent pricing changes.",
    description_bn: "AI দিয়ে প্রেজেন্টেশন বানান। একটা প্রম্পট থেকে পুরো স্লাইড ডেক।",
    review_bn: "ক্লায়েন্ট পিচের জন্য ৩০ মিনিটে প্রফেশনাল প্রেজেন্টেশন বানাই।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.6,
    direct_url: "https://gamma.app",
    affiliate_url: "https://gamma.app",
    pricing_url: "https://gamma.app/pricing",
  },
  {
    name: "Notion AI",
    logo: "https://logo.clearbit.com/notion.so",
    logo_fallback: "https://www.google.com/s2/favicons?domain=notion.so&sz=64",
    category: "productivity",
    pricing: "freemium",
    usdPrice: "Limited trial / Included in Business ($20/user/mo)",
    verified: "মার্চ ২০২৬",
    details: "AI features included in Business ($20/user/mo) and Enterprise plans. Free/Plus users get limited trial. Integrated AI approach.",
    description_bn: "Notion ওয়ার্কস্পেসে বিল্টইন AI। লেখা, সারসংক্ষেপ, ব্রেইনস্টর্মিং।",
    review_bn: "সব কন্টেন্ট প্ল্যানিং Notion-এ করি। AI ফিচার দিয়ে অনেক দ্রুত হয়।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.5,
    direct_url: "https://notion.so/product/ai",
    affiliate_url: "https://notion.so/affiliates",
    pricing_url: "https://www.notion.so/pricing",
  },
  {
    name: "Suno AI",
    logo: "https://logo.clearbit.com/suno.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=suno.com&sz=64",
    category: "productivity",
    pricing: "freemium",
    usdPrice: "Free (50 credits/day) / $10/mo (Pro) / $30/mo (Premier)",
    verified: "মার্চ ২০২৬",
    details: "Free tier with 50 daily credits. Pro $10/mo ($8 annually), Premier $30/mo. Commercial rights on paid plans.",
    description_bn: "টেক্সট থেকে পুরো গান তৈরি। লিরিক্স, মিউজিক, ভোকাল — সব AI দিয়ে।",
    review_bn: "ইউটিউব ভিডিওর জন্য ব্যাকগ্রাউন্ড মিউজিক তৈরি করি। কপিরাইট সমস্যা নেই।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.6,
    direct_url: "https://suno.com",
    affiliate_url: "https://suno.com",
    pricing_url: "https://suno.com/pricing",
  },
  {
    name: "Descript",
    logo: "https://logo.clearbit.com/descript.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=descript.com&sz=64",
    category: "productivity",
    pricing: "freemium",
    usdPrice: "Free (1 hour) / $24/user/mo (Hobbyist)",
    verified: "মার্চ ২০২৬",
    details: "Free plan with 1 hour transcription. Hobbyist $24/mo with 10 hours, 1080p export. AI video/podcast editor.",
    description_bn: "AI ভিডিও ও পডকাস্ট এডিটর। টেক্সট ডকুমেন্টের মতো ভিডিও এডিট করুন।",
    review_bn: "পডকাস্ট রেকর্ড করে Descript-এ এডিট করি। অনেক সহজ হয়ে গেছে।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.4,
    direct_url: "https://www.descript.com",
    affiliate_url: "https://www.descript.com",
    pricing_url: "https://www.descript.com/pricing",
  },
  {
    name: "Otter.ai",
    logo: "https://logo.clearbit.com/otter.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=otter.ai&sz=64",
    category: "productivity",
    pricing: "freemium",
    usdPrice: "Free / $17/mo",
    verified: "মার্চ ২০২৬",
    description_bn: "রিয়েল-টাইম মিটিং ট্রান্সক্রিপশন। অ্যাকশন আইটেম ও সারসংক্ষেপ অটো।",
    review_bn: "ক্লায়েন্ট কল রেকর্ড করি। পরে মিনিটস বানাতে কোনো সময় লাগে না।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.3,
    direct_url: "https://otter.ai",
    affiliate_url: "https://otter.ai",
    pricing_url: "https://otter.ai",
  },
  {
    name: "Zapier",
    logo: "https://logo.clearbit.com/zapier.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=zapier.com&sz=64",
    category: "productivity",
    pricing: "freemium",
    usdPrice: "Free (100 tasks) / $29.99/mo (Professional) / $103.50/mo (Team)",
    verified: "মার্চ ২০২৬",
    details: "Free tier with 100 tasks/mo. Professional $29.99/mo for 750 tasks. Team $103.50/mo for 2,000 tasks. Enterprise custom pricing.",
    description_bn: "৬০০০+ অ্যাপের মধ্যে AI-পাওয়ার্ড অটোমেশন। কোড ছাড়াই ওয়ার্কফ্লো।",
    review_bn: "Gmail থেকে Notion-এ অটো ডেটা যায়। ৩ ঘন্টার কাজ ০ মিনিটে!",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.5,
    direct_url: "https://zapier.com",
    affiliate_url: "https://zapier.com/affiliate",
    pricing_url: "https://zapier.com/pricing",
  },
  {
    name: "Make",
    logo: "https://logo.clearbit.com/make.com",
    logo_fallback: "https://www.google.com/s2/favicons?domain=make.com&sz=64",
    category: "productivity",
    pricing: "freemium",
    usdPrice: "Free (1,000 ops) / $10.59/mo (Core) / $18.82/mo (Pro)",
    verified: "মার্চ ২০২৬",
    details: "Free tier with 1,000 operations/mo. Core $10.59/mo for 10,000 ops. More cost-effective than Zapier at scale.",
    description_bn: "ভিজ্যুয়াল অটোমেশন প্ল্যাটফর্ম। AI-পাওয়ার্ড ওয়ার্কফ্লো ড্র্যাগ-অ্যান্ড-ড্রপে।",
    review_bn: "Zapier-এর চেয়ে সস্তা এবং আরও ফ্লেক্সিবল।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.5,
    direct_url: "https://www.make.com",
    affiliate_url: "https://www.make.com/en/affiliate-program",
    pricing_url: "https://www.make.com/en/pricing",
  },
  {
    name: "Jasper AI",
    logo: "https://logo.clearbit.com/jasper.ai",
    logo_fallback: "https://www.google.com/s2/favicons?domain=jasper.ai&sz=64",
    category: "productivity",
    pricing: "paid",
    usdPrice: "$59-69/mo (Pro) / Custom (Business)",
    verified: "মার্চ ২০২৬",
    details: "Pro plan $59/mo (annual) or $69/mo (monthly). Business plan custom pricing. 7-day free trial. AI marketing content platform.",
    description_bn: "মার্কেটিং টিমের জন্য AI কন্টেন্ট প্ল্যাটফর্ম। ব্লগ, বিজ্ঞাপন, ইমেইল স্কেলে।",
    review_bn: "ইংরেজি কন্টেন্ট মার্কেটিংয়ে ROI অনেক ভালো।",
    works_in_bd: true, no_vpn: true, payment: "card", rating: 4.2,
    direct_url: "https://www.jasper.ai",
    affiliate_url: "https://www.jasper.ai/affiliates",
    pricing_url: "https://www.jasper.ai/pricing",
  },
];
